// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: proto/chat/chat.proto

package chatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetChatIDByRoomIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomID        string                 `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	UserID        string                 `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatIDByRoomIDRequest) Reset() {
	*x = GetChatIDByRoomIDRequest{}
	mi := &file_proto_chat_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatIDByRoomIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatIDByRoomIDRequest) ProtoMessage() {}

func (x *GetChatIDByRoomIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatIDByRoomIDRequest.ProtoReflect.Descriptor instead.
func (*GetChatIDByRoomIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{0}
}

func (x *GetChatIDByRoomIDRequest) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

func (x *GetChatIDByRoomIDRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type ChatIDByRoomIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatID        string                 `protobuf:"bytes,2,opt,name=chatID,proto3" json:"chatID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatIDByRoomIDResponse) Reset() {
	*x = ChatIDByRoomIDResponse{}
	mi := &file_proto_chat_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatIDByRoomIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatIDByRoomIDResponse) ProtoMessage() {}

func (x *ChatIDByRoomIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatIDByRoomIDResponse.ProtoReflect.Descriptor instead.
func (*ChatIDByRoomIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ChatIDByRoomIDResponse) GetChatID() string {
	if x != nil {
		return x.ChatID
	}
	return ""
}

var File_proto_chat_chat_proto protoreflect.FileDescriptor

const file_proto_chat_chat_proto_rawDesc = "" +
	"\n" +
	"\x15proto/chat/chat.proto\x12\x04chat\"J\n" +
	"\x18GetChatIDByRoomIDRequest\x12\x16\n" +
	"\x06roomID\x18\x01 \x01(\tR\x06roomID\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\tR\x06userID\"0\n" +
	"\x16ChatIDByRoomIDResponse\x12\x16\n" +
	"\x06chatID\x18\x02 \x01(\tR\x06chatID2d\n" +
	"\x0fChatGrpcService\x12Q\n" +
	"\x11GetChatIDByRoomID\x12\x1e.chat.GetChatIDByRoomIDRequest\x1a\x1c.chat.ChatIDByRoomIDResponseB)Z'webby/vote-service/internal/grpc/chatpbb\x06proto3"

var (
	file_proto_chat_chat_proto_rawDescOnce sync.Once
	file_proto_chat_chat_proto_rawDescData []byte
)

func file_proto_chat_chat_proto_rawDescGZIP() []byte {
	file_proto_chat_chat_proto_rawDescOnce.Do(func() {
		file_proto_chat_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chat_chat_proto_rawDesc), len(file_proto_chat_chat_proto_rawDesc)))
	})
	return file_proto_chat_chat_proto_rawDescData
}

var file_proto_chat_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_chat_chat_proto_goTypes = []any{
	(*GetChatIDByRoomIDRequest)(nil), // 0: chat.GetChatIDByRoomIDRequest
	(*ChatIDByRoomIDResponse)(nil),   // 1: chat.ChatIDByRoomIDResponse
}
var file_proto_chat_chat_proto_depIdxs = []int32{
	0, // 0: chat.ChatGrpcService.GetChatIDByRoomID:input_type -> chat.GetChatIDByRoomIDRequest
	1, // 1: chat.ChatGrpcService.GetChatIDByRoomID:output_type -> chat.ChatIDByRoomIDResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_chat_chat_proto_init() }
func file_proto_chat_chat_proto_init() {
	if File_proto_chat_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chat_chat_proto_rawDesc), len(file_proto_chat_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chat_chat_proto_goTypes,
		DependencyIndexes: file_proto_chat_chat_proto_depIdxs,
		MessageInfos:      file_proto_chat_chat_proto_msgTypes,
	}.Build()
	File_proto_chat_chat_proto = out.File
	file_proto_chat_chat_proto_goTypes = nil
	file_proto_chat_chat_proto_depIdxs = nil
}
