// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: proto/media/media.proto

package mediapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoRequest) Reset() {
	*x = GetVideoRequest{}
	mi := &file_proto_media_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoRequest) ProtoMessage() {}

func (x *GetVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoRequest.ProtoReflect.Descriptor instead.
func (*GetVideoRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_media_proto_rawDescGZIP(), []int{0}
}

func (x *GetVideoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type VideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,3,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,4,opt,name=videoUrl,proto3" json:"videoUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoResponse) Reset() {
	*x = VideoResponse{}
	mi := &file_proto_media_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoResponse) ProtoMessage() {}

func (x *VideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoResponse.ProtoReflect.Descriptor instead.
func (*VideoResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_media_proto_rawDescGZIP(), []int{1}
}

func (x *VideoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VideoResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoResponse) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *VideoResponse) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

type GetVideosBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideosBatchRequest) Reset() {
	*x = GetVideosBatchRequest{}
	mi := &file_proto_media_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideosBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideosBatchRequest) ProtoMessage() {}

func (x *GetVideosBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideosBatchRequest.ProtoReflect.Descriptor instead.
func (*GetVideosBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_media_proto_rawDescGZIP(), []int{2}
}

func (x *GetVideosBatchRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetVideosBatchResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Videos              []*VideoResponse       `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	UnavailableVideoIds []string               `protobuf:"bytes,2,rep,name=unavailableVideoIds,proto3" json:"unavailableVideoIds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetVideosBatchResponse) Reset() {
	*x = GetVideosBatchResponse{}
	mi := &file_proto_media_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideosBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideosBatchResponse) ProtoMessage() {}

func (x *GetVideosBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideosBatchResponse.ProtoReflect.Descriptor instead.
func (*GetVideosBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_media_proto_rawDescGZIP(), []int{3}
}

func (x *GetVideosBatchResponse) GetVideos() []*VideoResponse {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *GetVideosBatchResponse) GetUnavailableVideoIds() []string {
	if x != nil {
		return x.UnavailableVideoIds
	}
	return nil
}

var File_proto_media_media_proto protoreflect.FileDescriptor

const file_proto_media_media_proto_rawDesc = "" +
	"\n" +
	"\x17proto/media/media.proto\x12\x05media\"!\n" +
	"\x0fGetVideoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"o\n" +
	"\rVideoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1c\n" +
	"\tthumbnail\x18\x03 \x01(\tR\tthumbnail\x12\x1a\n" +
	"\bvideoUrl\x18\x04 \x01(\tR\bvideoUrl\")\n" +
	"\x15GetVideosBatchRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"x\n" +
	"\x16GetVideosBatchResponse\x12,\n" +
	"\x06videos\x18\x01 \x03(\v2\x14.media.VideoResponseR\x06videos\x120\n" +
	"\x13unavailableVideoIds\x18\x02 \x03(\tR\x13unavailableVideoIds2\x97\x01\n" +
	"\fMediaService\x128\n" +
	"\bGetVideo\x12\x16.media.GetVideoRequest\x1a\x14.media.VideoResponse\x12M\n" +
	"\x0eGetVideosBatch\x12\x1c.media.GetVideosBatchRequest\x1a\x1d.media.GetVideosBatchResponseB0Z.webby/room-queue-service/internal/grpc/mediapbb\x06proto3"

var (
	file_proto_media_media_proto_rawDescOnce sync.Once
	file_proto_media_media_proto_rawDescData []byte
)

func file_proto_media_media_proto_rawDescGZIP() []byte {
	file_proto_media_media_proto_rawDescOnce.Do(func() {
		file_proto_media_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_media_media_proto_rawDesc), len(file_proto_media_media_proto_rawDesc)))
	})
	return file_proto_media_media_proto_rawDescData
}

var file_proto_media_media_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_media_media_proto_goTypes = []any{
	(*GetVideoRequest)(nil),        // 0: media.GetVideoRequest
	(*VideoResponse)(nil),          // 1: media.VideoResponse
	(*GetVideosBatchRequest)(nil),  // 2: media.GetVideosBatchRequest
	(*GetVideosBatchResponse)(nil), // 3: media.GetVideosBatchResponse
}
var file_proto_media_media_proto_depIdxs = []int32{
	1, // 0: media.GetVideosBatchResponse.videos:type_name -> media.VideoResponse
	0, // 1: media.MediaService.GetVideo:input_type -> media.GetVideoRequest
	2, // 2: media.MediaService.GetVideosBatch:input_type -> media.GetVideosBatchRequest
	1, // 3: media.MediaService.GetVideo:output_type -> media.VideoResponse
	3, // 4: media.MediaService.GetVideosBatch:output_type -> media.GetVideosBatchResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_media_media_proto_init() }
func file_proto_media_media_proto_init() {
	if File_proto_media_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_media_media_proto_rawDesc), len(file_proto_media_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_media_media_proto_goTypes,
		DependencyIndexes: file_proto_media_media_proto_depIdxs,
		MessageInfos:      file_proto_media_media_proto_msgTypes,
	}.Build()
	File_proto_media_media_proto = out.File
	file_proto_media_media_proto_goTypes = nil
	file_proto_media_media_proto_depIdxs = nil
}
