// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"context"
	"webby/internal/services"

	"github.com/google/uuid"
	"github.com/stretchr/testify/mock"
)

type MockGetter struct {
	mock.Mock
}

type MockGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetter) EXPECT() *MockGetter_Expecter {
	return &MockGetter_Expecter{mock: &_m.Mock}
}

func (_m *MockGetter) GetVote(ctx context.Context, voteId, userId uuid.UUID) (*services.VoteDetail, error) {
	ret := _m.Called(ctx, voteId, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetVote")
	}

	var r0 *services.VoteDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*services.VoteDetail, error)); ok {
		return rf(ctx, voteId, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *services.VoteDetail); ok {
		r0 = rf(ctx, voteId, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.VoteDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, voteId, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockGetter_GetVote_Call struct {
	*mock.Call
}

func (_e *MockGetter_Expecter) GetVote(ctx interface{}, voteId interface{}, userId interface{}) *MockGetter_GetVote_Call {
	return &MockGetter_GetVote_Call{Call: _e.mock.On("GetVote", ctx, voteId, userId)}
}

func (_c *MockGetter_GetVote_Call) Run(run func(ctx context.Context, voteId, userId uuid.UUID)) *MockGetter_GetVote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockGetter_GetVote_Call) Return(_a0 *services.VoteDetail, _a1 error) *MockGetter_GetVote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func NewMockGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetter {
	mock := &MockGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
