// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "webby/room-queue-service/internal/models"

	uuid "github.com/google/uuid"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AddToQueue provides a mock function with given fields: ctx, roomId, userId, entityId
func (_m *MockService) AddToQueue(ctx context.Context, roomId uuid.UUID, userId uuid.UUID, entityId string) (uuid.UUID, int, error) {
	ret := _m.Called(ctx, roomId, userId, entityId)

	if len(ret) == 0 {
		panic("no return value specified for AddToQueue")
	}

	var r0 uuid.UUID
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (uuid.UUID, int, error)); ok {
		return rf(ctx, roomId, userId, entityId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) uuid.UUID); ok {
		r0 = rf(ctx, roomId, userId, entityId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) int); ok {
		r1 = rf(ctx, roomId, userId, entityId)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r2 = rf(ctx, roomId, userId, entityId)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockService_AddToQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToQueue'
type MockService_AddToQueue_Call struct {
	*mock.Call
}

// AddToQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - roomId uuid.UUID
//   - userId uuid.UUID
//   - entityId string
func (_e *MockService_Expecter) AddToQueue(ctx interface{}, roomId interface{}, userId interface{}, entityId interface{}) *MockService_AddToQueue_Call {
	return &MockService_AddToQueue_Call{Call: _e.mock.On("AddToQueue", ctx, roomId, userId, entityId)}
}

func (_c *MockService_AddToQueue_Call) Run(run func(ctx context.Context, roomId uuid.UUID, userId uuid.UUID, entityId string)) *MockService_AddToQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockService_AddToQueue_Call) Return(_a0 uuid.UUID, _a1 int, _a2 error) *MockService_AddToQueue_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockService_AddToQueue_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) (uuid.UUID, int, error)) *MockService_AddToQueue_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFromQueue provides a mock function with given fields: ctx, itemId, userId
func (_m *MockService) DeleteFromQueue(ctx context.Context, itemId uuid.UUID, userId uuid.UUID) error {
	ret := _m.Called(ctx, itemId, userId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFromQueue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, itemId, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteFromQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFromQueue'
type MockService_DeleteFromQueue_Call struct {
	*mock.Call
}

// DeleteFromQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - itemId uuid.UUID
//   - userId uuid.UUID
func (_e *MockService_Expecter) DeleteFromQueue(ctx interface{}, itemId interface{}, userId interface{}) *MockService_DeleteFromQueue_Call {
	return &MockService_DeleteFromQueue_Call{Call: _e.mock.On("DeleteFromQueue", ctx, itemId, userId)}
}

func (_c *MockService_DeleteFromQueue_Call) Run(run func(ctx context.Context, itemId uuid.UUID, userId uuid.UUID)) *MockService_DeleteFromQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_DeleteFromQueue_Call) Return(_a0 error) *MockService_DeleteFromQueue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteFromQueue_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockService_DeleteFromQueue_Call {
	_c.Call.Return(run)
	return _c
}

// GetQueue provides a mock function with given fields: ctx, roomID, userID, page, limit
func (_m *MockService) GetQueue(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, page int, limit int) ([]models.EnrichedQueueItem, int, error) {
	ret := _m.Called(ctx, roomID, userID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetQueue")
	}

	var r0 []models.EnrichedQueueItem
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int) ([]models.EnrichedQueueItem, int, error)); ok {
		return rf(ctx, roomID, userID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int) []models.EnrichedQueueItem); ok {
		r0 = rf(ctx, roomID, userID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.EnrichedQueueItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, roomID, userID, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, roomID, userID, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockService_GetQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueue'
type MockService_GetQueue_Call struct {
	*mock.Call
}

// GetQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
//   - page int
//   - limit int
func (_e *MockService_Expecter) GetQueue(ctx interface{}, roomID interface{}, userID interface{}, page interface{}, limit interface{}) *MockService_GetQueue_Call {
	return &MockService_GetQueue_Call{Call: _e.mock.On("GetQueue", ctx, roomID, userID, page, limit)}
}

func (_c *MockService_GetQueue_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, page int, limit int)) *MockService_GetQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockService_GetQueue_Call) Return(_a0 []models.EnrichedQueueItem, _a1 int, _a2 error) *MockService_GetQueue_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockService_GetQueue_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, int, int) ([]models.EnrichedQueueItem, int, error)) *MockService_GetQueue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
