// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockQueueItemActivator is an autogenerated mock type for the QueueItemActivator type
type MockQueueItemActivator struct {
	mock.Mock
}

type MockQueueItemActivator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueueItemActivator) EXPECT() *MockQueueItemActivator_Expecter {
	return &MockQueueItemActivator_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, itemID, userID
func (_m *MockQueueItemActivator) Execute(ctx context.Context, itemID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, itemID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, itemID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQueueItemActivator_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockQueueItemActivator_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - itemID uuid.UUID
//   - userID uuid.UUID
func (_e *MockQueueItemActivator_Expecter) Execute(ctx interface{}, itemID interface{}, userID interface{}) *MockQueueItemActivator_Execute_Call {
	return &MockQueueItemActivator_Execute_Call{Call: _e.mock.On("Execute", ctx, itemID, userID)}
}

func (_c *MockQueueItemActivator_Execute_Call) Run(run func(ctx context.Context, itemID uuid.UUID, userID uuid.UUID)) *MockQueueItemActivator_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockQueueItemActivator_Execute_Call) Return(_a0 error) *MockQueueItemActivator_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueueItemActivator_Execute_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockQueueItemActivator_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueueItemActivator creates a new instance of MockQueueItemActivator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueueItemActivator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueueItemActivator {
	mock := &MockQueueItemActivator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
