// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "webby/internal/models"

	uuid "github.com/google/uuid"
)

// MockGetter is an autogenerated mock type for the Getter type
type MockGetter struct {
	mock.Mock
}

type MockGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetter) EXPECT() *MockGetter_Expecter {
	return &MockGetter_Expecter{mock: &_m.Mock}
}

// GetById provides a mock function with given fields: ctx, roomId, userId
func (_m *MockGetter) GetById(ctx context.Context, roomId uuid.UUID, userId uuid.UUID) (*models.Room, error) {
	ret := _m.Called(ctx, roomId, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *models.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.Room, error)); ok {
		return rf(ctx, roomId, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.Room); ok {
		r0 = rf(ctx, roomId, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, roomId, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetter_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockGetter_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - roomId uuid.UUID
//   - userId uuid.UUID
func (_e *MockGetter_Expecter) GetById(ctx interface{}, roomId interface{}, userId interface{}) *MockGetter_GetById_Call {
	return &MockGetter_GetById_Call{Call: _e.mock.On("GetById", ctx, roomId, userId)}
}

func (_c *MockGetter_GetById_Call) Run(run func(ctx context.Context, roomId uuid.UUID, userId uuid.UUID)) *MockGetter_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockGetter_GetById_Call) Return(_a0 *models.Room, _a1 error) *MockGetter_GetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetter_GetById_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*models.Room, error)) *MockGetter_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetter creates a new instance of MockGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetter {
	mock := &MockGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
