// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockPointsUpdater is an autogenerated mock type for the PointsUpdater type
type MockPointsUpdater struct {
	mock.Mock
}

type MockPointsUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPointsUpdater) EXPECT() *MockPointsUpdater_Expecter {
	return &MockPointsUpdater_Expecter{mock: &_m.Mock}
}

// UpdateMemberPoints provides a mock function with given fields: ctx, roomId, memberId, delta, userId
func (_m *MockPointsUpdater) UpdateMemberPoints(ctx context.Context, roomId uuid.UUID, memberId uuid.UUID, delta int, userId uuid.UUID) error {
	ret := _m.Called(ctx, roomId, memberId, delta, userId)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMemberPoints")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, uuid.UUID) error); ok {
		r0 = rf(ctx, roomId, memberId, delta, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPointsUpdater_UpdateMemberPoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMemberPoints'
type MockPointsUpdater_UpdateMemberPoints_Call struct {
	*mock.Call
}

// UpdateMemberPoints is a helper method to define mock.On call
//   - ctx context.Context
//   - roomId uuid.UUID
//   - memberId uuid.UUID
//   - delta int
//   - userId uuid.UUID
func (_e *MockPointsUpdater_Expecter) UpdateMemberPoints(ctx interface{}, roomId interface{}, memberId interface{}, delta interface{}, userId interface{}) *MockPointsUpdater_UpdateMemberPoints_Call {
	return &MockPointsUpdater_UpdateMemberPoints_Call{Call: _e.mock.On("UpdateMemberPoints", ctx, roomId, memberId, delta, userId)}
}

func (_c *MockPointsUpdater_UpdateMemberPoints_Call) Run(run func(ctx context.Context, roomId uuid.UUID, memberId uuid.UUID, delta int, userId uuid.UUID)) *MockPointsUpdater_UpdateMemberPoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(int), args[4].(uuid.UUID))
	})
	return _c
}

func (_c *MockPointsUpdater_UpdateMemberPoints_Call) Return(_a0 error) *MockPointsUpdater_UpdateMemberPoints_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPointsUpdater_UpdateMemberPoints_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, int, uuid.UUID) error) *MockPointsUpdater_UpdateMemberPoints_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPointsUpdater creates a new instance of MockPointsUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPointsUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPointsUpdater {
	mock := &MockPointsUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
