// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: member/member.proto

package memberpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MemberGrpcService_MemberExists_FullMethodName = "/member.MemberGrpcService/MemberExists"
)

// MemberGrpcServiceClient is the client API for MemberGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MemberGrpcServiceClient interface {
	MemberExists(ctx context.Context, in *MemberExistsRequest, opts ...grpc.CallOption) (*MemberExistsResponse, error)
}

type memberGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMemberGrpcServiceClient(cc grpc.ClientConnInterface) MemberGrpcServiceClient {
	return &memberGrpcServiceClient{cc}
}

func (c *memberGrpcServiceClient) MemberExists(ctx context.Context, in *MemberExistsRequest, opts ...grpc.CallOption) (*MemberExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemberExistsResponse)
	err := c.cc.Invoke(ctx, MemberGrpcService_MemberExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemberGrpcServiceServer is the server API for MemberGrpcService service.
// All implementations must embed UnimplementedMemberGrpcServiceServer
// for forward compatibility.
type MemberGrpcServiceServer interface {
	MemberExists(context.Context, *MemberExistsRequest) (*MemberExistsResponse, error)
	mustEmbedUnimplementedMemberGrpcServiceServer()
}

// UnimplementedMemberGrpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMemberGrpcServiceServer struct{}

func (UnimplementedMemberGrpcServiceServer) MemberExists(context.Context, *MemberExistsRequest) (*MemberExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MemberExists not implemented")
}
func (UnimplementedMemberGrpcServiceServer) mustEmbedUnimplementedMemberGrpcServiceServer() {}
func (UnimplementedMemberGrpcServiceServer) testEmbeddedByValue()                           {}

// UnsafeMemberGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemberGrpcServiceServer will
// result in compilation errors.
type UnsafeMemberGrpcServiceServer interface {
	mustEmbedUnimplementedMemberGrpcServiceServer()
}

func RegisterMemberGrpcServiceServer(s grpc.ServiceRegistrar, srv MemberGrpcServiceServer) {
	// If the following call panics, it indicates UnimplementedMemberGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MemberGrpcService_ServiceDesc, srv)
}

func _MemberGrpcService_MemberExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberGrpcServiceServer).MemberExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemberGrpcService_MemberExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberGrpcServiceServer).MemberExists(ctx, req.(*MemberExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MemberGrpcService_ServiceDesc is the grpc.ServiceDesc for MemberGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MemberGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "member.MemberGrpcService",
	HandlerType: (*MemberGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MemberExists",
			Handler:    _MemberGrpcService_MemberExists_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "member/member.proto",
}
