apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: user-service
          image: eu-frankfurt-1.ocir.io/fr3wma7oqvij/webby-user-service:latest
          ports:
            - containerPort: 5002 # REST
            - containerPort: 5004 # gRPC
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ConnectionStrings__AppDbContext
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: DatabaseConnectionString
            - name: ConnectionStrings__Redis
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: RedisDbConnectionString
            - name: AwsOptions__AccessKey
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: AwsAccessKey
            - name: AwsOptions__SecretKey
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: AwsSecretKey
            - name: AwsOptions__BucketName
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: AwsBucketName
            - name: AwsOptions__Region
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: AwsRegion
            - name: PaymentOptions__PaymentPublicKey
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: StripePublishableKey
            - name: PaymentOptions__PaymentSecretKey
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: StripeSecretKey
            - name: PaymentOptions__PaymentWebhookKey
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: StripeWebhookKey
            - name: PaymentOptions__SuccessUrl
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: PaymentSuccessUrl
            - name: PaymentOptions__CancelUrl
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: PaymentCancelUrl
            - name: AutoMapper__LicenseKey
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: AutoMapperLicenseKey
            - name: GrpcClients__VideoServiceUrl
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: VideoGrpcServiceUrl
            - name: GrpcClients__NotificationServiceUrl
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: NotificationGrpcServiceUrl
            - name: GrpcClients__AchievementServiceUrl
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: AchievementGrpcServiceUrl
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /livez
              port: 5002
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 5002
            initialDelaySeconds: 10
            periodSeconds: 10
