syntax = "proto3";

package chat;

option go_package = "webby/chat-service/internal/grpc/chatpb";

service ChatGrpcService {
  rpc CreateChat(CreateChatRequest) returns (ChatResponse);
  rpc GetChatByRoomId(GetChatByRoomIdRequest) returns (ChatResponse);
  rpc AddChatMember(AddChatMemberRequest) returns (AddChatMemberResponse);
  rpc SaveMessage(SaveMessageRequest) returns (SaveMessageResponse);
}

message CreateChatRequest {
  string room_id = 1;
}

message GetChatByRoomIdRequest {
  string room_id = 1;
}

message AddChatMemberRequest {
  string chat_id = 1;
  string user_id = 2;
}

message SaveMessageRequest {
  string chat_id = 1;
  string user_id = 2;
  string content = 3;
}

message SaveMessageResponse {
  string message_id = 1;
}

message ChatResponse {
  string id = 1;
  string room_id = 2;
}

message AddChatMemberResponse {}
