syntax = "proto3";

option csharp_namespace = "UserService";

service UserGrpcService {
  rpc GetUserById (GetUserRequest) returns (UserResponse);
  rpc GetUsersByIds (GetUsersRequest) returns (GetUsersResponse);
  rpc GetUserSubscriptionIds (GetUserSubscriptionIdsRequest) returns (GetUserSubscriptionsIdsResponse);
  rpc GetPremiumStatus(GetPremiumStatusRequest) returns (GetPremiumStatusResponse);
  rpc FindUserIDs(FindUserIDsRequest) returns (FindUserIDsResponse);
  rpc IsFollowed(IsFollowedRequest) returns (IsFollowedResponse);
}

// REQUESTS

message GetUserRequest {
  string userId = 1;
  optional string requestUserId = 2;
}

message GetUsersRequest {
  repeated string userIds = 1;
}

message GetUserSubscriptionIdsRequest{
  string requestUserId = 1;
}

message GetPremiumStatusRequest{
  string userId = 1;
}

message FindUserIDsRequest {
  repeated string userIds = 1;
  string search = 2;
  int32 offset = 3;
  int32 limit = 4;
}

message IsFollowedRequest {
  string firstUserId = 1;
  string secondUserId = 2;
}

//RESPONSES

message UserResponse {
  string userId = 1;
  string username = 2;
  string avatarUrl = 3;
  bool isFollowed = 4;
}

message GetUsersResponse {
  repeated UserResponse users = 1;
}

message GetUserSubscriptionsIdsResponse{
  repeated string userIds = 1;
}

enum PremiumStatus {
  NONE = 0;
  ACTIVE = 1;
  EXPIRED = 2;
  TRIAL = 3;
}

message GetPremiumStatusResponse {
  PremiumStatus status = 1;
}

message FindUserIDsResponse {
  repeated string userIds = 1;
}

message IsFollowedResponse {
  bool isFollowed = 1;
}