// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockMemberRemover is an autogenerated mock type for the MemberRemover type
type MockMemberRemover struct {
	mock.Mock
}

type MockMemberRemover_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMemberRemover) EXPECT() *MockMemberRemover_Expecter {
	return &MockMemberRemover_Expecter{mock: &_m.Mock}
}

// RemoveMember provides a mock function with given fields: ctx, roomId, memberId, userId
func (_m *MockMemberRemover) RemoveMember(ctx context.Context, roomId uuid.UUID, memberId uuid.UUID, userId uuid.UUID) error {
	ret := _m.Called(ctx, roomId, memberId, userId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, roomId, memberId, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMemberRemover_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type MockMemberRemover_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - roomId uuid.UUID
//   - memberId uuid.UUID
//   - userId uuid.UUID
func (_e *MockMemberRemover_Expecter) RemoveMember(ctx interface{}, roomId interface{}, memberId interface{}, userId interface{}) *MockMemberRemover_RemoveMember_Call {
	return &MockMemberRemover_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, roomId, memberId, userId)}
}

func (_c *MockMemberRemover_RemoveMember_Call) Run(run func(ctx context.Context, roomId uuid.UUID, memberId uuid.UUID, userId uuid.UUID)) *MockMemberRemover_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockMemberRemover_RemoveMember_Call) Return(_a0 error) *MockMemberRemover_RemoveMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMemberRemover_RemoveMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) *MockMemberRemover_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMemberRemover creates a new instance of MockMemberRemover. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMemberRemover(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMemberRemover {
	mock := &MockMemberRemover{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
