// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: proto/chat/chat.proto

package chatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomID        string                 `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatRequest) Reset() {
	*x = CreateChatRequest{}
	mi := &file_proto_chat_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatRequest) ProtoMessage() {}

func (x *CreateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatRequest.ProtoReflect.Descriptor instead.
func (*CreateChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{0}
}

func (x *CreateChatRequest) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

type GetChatByRoomIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomID        string                 `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatByRoomIdRequest) Reset() {
	*x = GetChatByRoomIdRequest{}
	mi := &file_proto_chat_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatByRoomIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatByRoomIdRequest) ProtoMessage() {}

func (x *GetChatByRoomIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatByRoomIdRequest.ProtoReflect.Descriptor instead.
func (*GetChatByRoomIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{1}
}

func (x *GetChatByRoomIdRequest) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

type AddChatMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatID        string                 `protobuf:"bytes,1,opt,name=chatID,proto3" json:"chatID,omitempty"`
	UserID        string                 `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddChatMemberRequest) Reset() {
	*x = AddChatMemberRequest{}
	mi := &file_proto_chat_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddChatMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddChatMemberRequest) ProtoMessage() {}

func (x *AddChatMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddChatMemberRequest.ProtoReflect.Descriptor instead.
func (*AddChatMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{2}
}

func (x *AddChatMemberRequest) GetChatID() string {
	if x != nil {
		return x.ChatID
	}
	return ""
}

func (x *AddChatMemberRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomID        string                 `protobuf:"bytes,2,opt,name=roomID,proto3" json:"roomID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_proto_chat_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ChatResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatResponse) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

type AddChatMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddChatMemberResponse) Reset() {
	*x = AddChatMemberResponse{}
	mi := &file_proto_chat_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddChatMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddChatMemberResponse) ProtoMessage() {}

func (x *AddChatMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddChatMemberResponse.ProtoReflect.Descriptor instead.
func (*AddChatMemberResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{4}
}

type GetChatIDByRoomIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomID        string                 `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatIDByRoomIDRequest) Reset() {
	*x = GetChatIDByRoomIDRequest{}
	mi := &file_proto_chat_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatIDByRoomIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatIDByRoomIDRequest) ProtoMessage() {}

func (x *GetChatIDByRoomIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatIDByRoomIDRequest.ProtoReflect.Descriptor instead.
func (*GetChatIDByRoomIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{5}
}

func (x *GetChatIDByRoomIDRequest) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

type ChatIDByRoomIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatID        string                 `protobuf:"bytes,2,opt,name=chatID,proto3" json:"chatID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatIDByRoomIDResponse) Reset() {
	*x = ChatIDByRoomIDResponse{}
	mi := &file_proto_chat_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatIDByRoomIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatIDByRoomIDResponse) ProtoMessage() {}

func (x *ChatIDByRoomIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatIDByRoomIDResponse.ProtoReflect.Descriptor instead.
func (*ChatIDByRoomIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{6}
}

func (x *ChatIDByRoomIDResponse) GetChatID() string {
	if x != nil {
		return x.ChatID
	}
	return ""
}

type RoomIDByChatIDBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatIDs       []string               `protobuf:"bytes,1,rep,name=chatIDs,proto3" json:"chatIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomIDByChatIDBatchRequest) Reset() {
	*x = RoomIDByChatIDBatchRequest{}
	mi := &file_proto_chat_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomIDByChatIDBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomIDByChatIDBatchRequest) ProtoMessage() {}

func (x *RoomIDByChatIDBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomIDByChatIDBatchRequest.ProtoReflect.Descriptor instead.
func (*RoomIDByChatIDBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{7}
}

func (x *RoomIDByChatIDBatchRequest) GetChatIDs() []string {
	if x != nil {
		return x.ChatIDs
	}
	return nil
}

type RoomIDByChatIDBatchResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChatIDroomIDMap map[string]string      `protobuf:"bytes,1,rep,name=chatIDroomIDMap,proto3" json:"chatIDroomIDMap,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RoomIDByChatIDBatchResponse) Reset() {
	*x = RoomIDByChatIDBatchResponse{}
	mi := &file_proto_chat_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomIDByChatIDBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomIDByChatIDBatchResponse) ProtoMessage() {}

func (x *RoomIDByChatIDBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomIDByChatIDBatchResponse.ProtoReflect.Descriptor instead.
func (*RoomIDByChatIDBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{8}
}

func (x *RoomIDByChatIDBatchResponse) GetChatIDroomIDMap() map[string]string {
	if x != nil {
		return x.ChatIDroomIDMap
	}
	return nil
}

var File_proto_chat_chat_proto protoreflect.FileDescriptor

const file_proto_chat_chat_proto_rawDesc = "" +
	"\n" +
	"\x15proto/chat/chat.proto\x12\x04chat\"+\n" +
	"\x11CreateChatRequest\x12\x16\n" +
	"\x06roomID\x18\x01 \x01(\tR\x06roomID\"0\n" +
	"\x16GetChatByRoomIdRequest\x12\x16\n" +
	"\x06roomID\x18\x01 \x01(\tR\x06roomID\"F\n" +
	"\x14AddChatMemberRequest\x12\x16\n" +
	"\x06chatID\x18\x01 \x01(\tR\x06chatID\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\tR\x06userID\"6\n" +
	"\fChatResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06roomID\x18\x02 \x01(\tR\x06roomID\"\x17\n" +
	"\x15AddChatMemberResponse\"2\n" +
	"\x18GetChatIDByRoomIDRequest\x12\x16\n" +
	"\x06roomID\x18\x01 \x01(\tR\x06roomID\"0\n" +
	"\x16ChatIDByRoomIDResponse\x12\x16\n" +
	"\x06chatID\x18\x02 \x01(\tR\x06chatID\"6\n" +
	"\x1aRoomIDByChatIDBatchRequest\x12\x18\n" +
	"\achatIDs\x18\x01 \x03(\tR\achatIDs\"\xc3\x01\n" +
	"\x1bRoomIDByChatIDBatchResponse\x12`\n" +
	"\x0fchatIDroomIDMap\x18\x01 \x03(\v26.chat.RoomIDByChatIDBatchResponse.ChatIDroomIDMapEntryR\x0fchatIDroomIDMap\x1aB\n" +
	"\x14ChatIDroomIDMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x8a\x03\n" +
	"\x0fChatGrpcService\x129\n" +
	"\n" +
	"CreateChat\x12\x17.chat.CreateChatRequest\x1a\x12.chat.ChatResponse\x12C\n" +
	"\x0fGetChatByRoomID\x12\x1c.chat.GetChatByRoomIdRequest\x1a\x12.chat.ChatResponse\x12H\n" +
	"\rAddChatMember\x12\x1a.chat.AddChatMemberRequest\x1a\x1b.chat.AddChatMemberResponse\x12Q\n" +
	"\x11GetChatIDByRoomID\x12\x1e.chat.GetChatIDByRoomIDRequest\x1a\x1c.chat.ChatIDByRoomIDResponse\x12Z\n" +
	"\x13RoomIDByChatIDBatch\x12 .chat.RoomIDByChatIDBatchRequest\x1a!.chat.RoomIDByChatIDBatchResponseB)Z'webby/room-service/internal/grpc/chatpbb\x06proto3"

var (
	file_proto_chat_chat_proto_rawDescOnce sync.Once
	file_proto_chat_chat_proto_rawDescData []byte
)

func file_proto_chat_chat_proto_rawDescGZIP() []byte {
	file_proto_chat_chat_proto_rawDescOnce.Do(func() {
		file_proto_chat_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chat_chat_proto_rawDesc), len(file_proto_chat_chat_proto_rawDesc)))
	})
	return file_proto_chat_chat_proto_rawDescData
}

var file_proto_chat_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_chat_chat_proto_goTypes = []any{
	(*CreateChatRequest)(nil),           // 0: chat.CreateChatRequest
	(*GetChatByRoomIdRequest)(nil),      // 1: chat.GetChatByRoomIdRequest
	(*AddChatMemberRequest)(nil),        // 2: chat.AddChatMemberRequest
	(*ChatResponse)(nil),                // 3: chat.ChatResponse
	(*AddChatMemberResponse)(nil),       // 4: chat.AddChatMemberResponse
	(*GetChatIDByRoomIDRequest)(nil),    // 5: chat.GetChatIDByRoomIDRequest
	(*ChatIDByRoomIDResponse)(nil),      // 6: chat.ChatIDByRoomIDResponse
	(*RoomIDByChatIDBatchRequest)(nil),  // 7: chat.RoomIDByChatIDBatchRequest
	(*RoomIDByChatIDBatchResponse)(nil), // 8: chat.RoomIDByChatIDBatchResponse
	nil,                                 // 9: chat.RoomIDByChatIDBatchResponse.ChatIDroomIDMapEntry
}
var file_proto_chat_chat_proto_depIdxs = []int32{
	9, // 0: chat.RoomIDByChatIDBatchResponse.chatIDroomIDMap:type_name -> chat.RoomIDByChatIDBatchResponse.ChatIDroomIDMapEntry
	0, // 1: chat.ChatGrpcService.CreateChat:input_type -> chat.CreateChatRequest
	1, // 2: chat.ChatGrpcService.GetChatByRoomID:input_type -> chat.GetChatByRoomIdRequest
	2, // 3: chat.ChatGrpcService.AddChatMember:input_type -> chat.AddChatMemberRequest
	5, // 4: chat.ChatGrpcService.GetChatIDByRoomID:input_type -> chat.GetChatIDByRoomIDRequest
	7, // 5: chat.ChatGrpcService.RoomIDByChatIDBatch:input_type -> chat.RoomIDByChatIDBatchRequest
	3, // 6: chat.ChatGrpcService.CreateChat:output_type -> chat.ChatResponse
	3, // 7: chat.ChatGrpcService.GetChatByRoomID:output_type -> chat.ChatResponse
	4, // 8: chat.ChatGrpcService.AddChatMember:output_type -> chat.AddChatMemberResponse
	6, // 9: chat.ChatGrpcService.GetChatIDByRoomID:output_type -> chat.ChatIDByRoomIDResponse
	8, // 10: chat.ChatGrpcService.RoomIDByChatIDBatch:output_type -> chat.RoomIDByChatIDBatchResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_chat_chat_proto_init() }
func file_proto_chat_chat_proto_init() {
	if File_proto_chat_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chat_chat_proto_rawDesc), len(file_proto_chat_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chat_chat_proto_goTypes,
		DependencyIndexes: file_proto_chat_chat_proto_depIdxs,
		MessageInfos:      file_proto_chat_chat_proto_msgTypes,
	}.Build()
	File_proto_chat_chat_proto = out.File
	file_proto_chat_chat_proto_goTypes = nil
	file_proto_chat_chat_proto_depIdxs = nil
}
