// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: proto/chat/chat.proto

package chatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsChatRelatedToRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatID        string                 `protobuf:"bytes,1,opt,name=chatID,proto3" json:"chatID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsChatRelatedToRoomRequest) Reset() {
	*x = IsChatRelatedToRoomRequest{}
	mi := &file_proto_chat_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsChatRelatedToRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsChatRelatedToRoomRequest) ProtoMessage() {}

func (x *IsChatRelatedToRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsChatRelatedToRoomRequest.ProtoReflect.Descriptor instead.
func (*IsChatRelatedToRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{0}
}

func (x *IsChatRelatedToRoomRequest) GetChatID() string {
	if x != nil {
		return x.ChatID
	}
	return ""
}

type IsChatRelatedToRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsRelated     bool                   `protobuf:"varint,1,opt,name=isRelated,proto3" json:"isRelated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsChatRelatedToRoomResponse) Reset() {
	*x = IsChatRelatedToRoomResponse{}
	mi := &file_proto_chat_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsChatRelatedToRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsChatRelatedToRoomResponse) ProtoMessage() {}

func (x *IsChatRelatedToRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsChatRelatedToRoomResponse.ProtoReflect.Descriptor instead.
func (*IsChatRelatedToRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{1}
}

func (x *IsChatRelatedToRoomResponse) GetIsRelated() bool {
	if x != nil {
		return x.IsRelated
	}
	return false
}

var File_proto_chat_chat_proto protoreflect.FileDescriptor

const file_proto_chat_chat_proto_rawDesc = "" +
	"\n" +
	"\x15proto/chat/chat.proto\x12\x04chat\"4\n" +
	"\x1aIsChatRelatedToRoomRequest\x12\x16\n" +
	"\x06chatID\x18\x01 \x01(\tR\x06chatID\";\n" +
	"\x1bIsChatRelatedToRoomResponse\x12\x1c\n" +
	"\tisRelated\x18\x01 \x01(\bR\tisRelated2m\n" +
	"\x0fChatGrpcService\x12Z\n" +
	"\x13IsChatRelatedToRoom\x12 .chat.IsChatRelatedToRoomRequest\x1a!.chat.IsChatRelatedToRoomResponseB&Z$webby/wsgateway/internal/grpc/chatpbb\x06proto3"

var (
	file_proto_chat_chat_proto_rawDescOnce sync.Once
	file_proto_chat_chat_proto_rawDescData []byte
)

func file_proto_chat_chat_proto_rawDescGZIP() []byte {
	file_proto_chat_chat_proto_rawDescOnce.Do(func() {
		file_proto_chat_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chat_chat_proto_rawDesc), len(file_proto_chat_chat_proto_rawDesc)))
	})
	return file_proto_chat_chat_proto_rawDescData
}

var file_proto_chat_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_chat_chat_proto_goTypes = []any{
	(*IsChatRelatedToRoomRequest)(nil),  // 0: chat.IsChatRelatedToRoomRequest
	(*IsChatRelatedToRoomResponse)(nil), // 1: chat.IsChatRelatedToRoomResponse
}
var file_proto_chat_chat_proto_depIdxs = []int32{
	0, // 0: chat.ChatGrpcService.IsChatRelatedToRoom:input_type -> chat.IsChatRelatedToRoomRequest
	1, // 1: chat.ChatGrpcService.IsChatRelatedToRoom:output_type -> chat.IsChatRelatedToRoomResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_chat_chat_proto_init() }
func file_proto_chat_chat_proto_init() {
	if File_proto_chat_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chat_chat_proto_rawDesc), len(file_proto_chat_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chat_chat_proto_goTypes,
		DependencyIndexes: file_proto_chat_chat_proto_depIdxs,
		MessageInfos:      file_proto_chat_chat_proto_msgTypes,
	}.Build()
	File_proto_chat_chat_proto = out.File
	file_proto_chat_chat_proto_goTypes = nil
	file_proto_chat_chat_proto_depIdxs = nil
}
