with-expecter: true
issue-845-fix: true
disable-version-string: true
all: true

dir: "{{.InterfaceDir}}/mocks"
outpkg: "mocks"
filename: "mock_{{.InterfaceNameCamel}}.go"
mockname: "Mock{{.InterfaceName}}"

packages:
  webby/room-service/internal/handlers:
    config:
      recursive: false