// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/stretchr/testify/mock"
)

type MockDeleter struct {
	mock.Mock
}

type MockDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleter) EXPECT() *MockDeleter_Expecter {
	return &MockDeleter_Expecter{mock: &_m.Mock}
}

func (_m *MockDeleter) DeleteVote(ctx context.Context, voteId, userId uuid.UUID) error {
	ret := _m.Called(ctx, voteId, userId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, voteId, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type MockDeleter_DeleteVote_Call struct {
	*mock.Call
}

func (_e *MockDeleter_Expecter) DeleteVote(ctx interface{}, voteId interface{}, userId interface{}) *MockDeleter_DeleteVote_Call {
	return &MockDeleter_DeleteVote_Call{Call: _e.mock.On("DeleteVote", ctx, voteId, userId)}
}

func (_c *MockDeleter_DeleteVote_Call) Run(run func(ctx context.Context, voteId, userId uuid.UUID)) *MockDeleter_DeleteVote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockDeleter_DeleteVote_Call) Return(_a0 error) *MockDeleter_DeleteVote_Call {
	_c.Call.Return(_a0)
	return _c
}

func NewMockDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeleter {
	mock := &MockDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
