// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: proto/room/room.proto

package roompb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AwardActiveUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RoomActivity        `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwardActiveUsersRequest) Reset() {
	*x = AwardActiveUsersRequest{}
	mi := &file_proto_room_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwardActiveUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwardActiveUsersRequest) ProtoMessage() {}

func (x *AwardActiveUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwardActiveUsersRequest.ProtoReflect.Descriptor instead.
func (*AwardActiveUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{0}
}

func (x *AwardActiveUsersRequest) GetRooms() []*RoomActivity {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type RoomActivity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserIds       []string               `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomActivity) Reset() {
	*x = RoomActivity{}
	mi := &file_proto_room_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomActivity) ProtoMessage() {}

func (x *RoomActivity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomActivity.ProtoReflect.Descriptor instead.
func (*RoomActivity) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{1}
}

func (x *RoomActivity) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomActivity) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type AwardActiveUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwardActiveUsersResponse) Reset() {
	*x = AwardActiveUsersResponse{}
	mi := &file_proto_room_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwardActiveUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwardActiveUsersResponse) ProtoMessage() {}

func (x *AwardActiveUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwardActiveUsersResponse.ProtoReflect.Descriptor instead.
func (*AwardActiveUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{2}
}

var File_proto_room_room_proto protoreflect.FileDescriptor

const file_proto_room_room_proto_rawDesc = "" +
	"\n" +
	"\x15proto/room/room.proto\x12\x04room\"C\n" +
	"\x17AwardActiveUsersRequest\x12(\n" +
	"\x05rooms\x18\x01 \x03(\v2\x12.room.RoomActivityR\x05rooms\"B\n" +
	"\fRoomActivity\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\tR\auserIds\"\x1a\n" +
	"\x18AwardActiveUsersResponse2d\n" +
	"\x0fRoomGrpcService\x12Q\n" +
	"\x10AwardActiveUsers\x12\x1d.room.AwardActiveUsersRequest\x1a\x1e.room.AwardActiveUsersResponseB&Z$webby-wsgateway/internal/grpc/roompbb\x06proto3"

var (
	file_proto_room_room_proto_rawDescOnce sync.Once
	file_proto_room_room_proto_rawDescData []byte
)

func file_proto_room_room_proto_rawDescGZIP() []byte {
	file_proto_room_room_proto_rawDescOnce.Do(func() {
		file_proto_room_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_room_room_proto_rawDesc), len(file_proto_room_room_proto_rawDesc)))
	})
	return file_proto_room_room_proto_rawDescData
}

var file_proto_room_room_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_room_room_proto_goTypes = []any{
	(*AwardActiveUsersRequest)(nil),  // 0: room.AwardActiveUsersRequest
	(*RoomActivity)(nil),             // 1: room.RoomActivity
	(*AwardActiveUsersResponse)(nil), // 2: room.AwardActiveUsersResponse
}
var file_proto_room_room_proto_depIdxs = []int32{
	1, // 0: room.AwardActiveUsersRequest.rooms:type_name -> room.RoomActivity
	0, // 1: room.RoomGrpcService.AwardActiveUsers:input_type -> room.AwardActiveUsersRequest
	2, // 2: room.RoomGrpcService.AwardActiveUsers:output_type -> room.AwardActiveUsersResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_room_room_proto_init() }
func file_proto_room_room_proto_init() {
	if File_proto_room_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_room_room_proto_rawDesc), len(file_proto_room_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_room_room_proto_goTypes,
		DependencyIndexes: file_proto_room_room_proto_depIdxs,
		MessageInfos:      file_proto_room_room_proto_msgTypes,
	}.Build()
	File_proto_room_room_proto = out.File
	file_proto_room_room_proto_goTypes = nil
	file_proto_room_room_proto_depIdxs = nil
}
