// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Mockservice is an autogenerated mock type for the service type
type Mockservice struct {
	mock.Mock
}

type Mockservice_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockservice) EXPECT() *Mockservice_Expecter {
	return &Mockservice_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, name
func (_m *Mockservice) Create(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mockservice_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Mockservice_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *Mockservice_Expecter) Create(ctx interface{}, name interface{}) *Mockservice_Create_Call {
	return &Mockservice_Create_Call{Call: _e.mock.On("Create", ctx, name)}
}

func (_c *Mockservice_Create_Call) Run(run func(ctx context.Context, name string)) *Mockservice_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Mockservice_Create_Call) Return(_a0 error) *Mockservice_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mockservice_Create_Call) RunAndReturn(run func(context.Context, string) error) *Mockservice_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name
func (_m *Mockservice) Delete(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mockservice_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Mockservice_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *Mockservice_Expecter) Delete(ctx interface{}, name interface{}) *Mockservice_Delete_Call {
	return &Mockservice_Delete_Call{Call: _e.mock.On("Delete", ctx, name)}
}

func (_c *Mockservice_Delete_Call) Run(run func(ctx context.Context, name string)) *Mockservice_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Mockservice_Delete_Call) Return(_a0 error) *Mockservice_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mockservice_Delete_Call) RunAndReturn(run func(context.Context, string) error) *Mockservice_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, search, page, limit
func (_m *Mockservice) List(ctx context.Context, search string, page int, limit int) ([]string, int, error) {
	ret := _m.Called(ctx, search, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []string
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]string, int, error)); ok {
		return rf(ctx, search, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []string); ok {
		r0 = rf(ctx, search, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, search, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, search, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Mockservice_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Mockservice_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - search string
//   - page int
//   - limit int
func (_e *Mockservice_Expecter) List(ctx interface{}, search interface{}, page interface{}, limit interface{}) *Mockservice_List_Call {
	return &Mockservice_List_Call{Call: _e.mock.On("List", ctx, search, page, limit)}
}

func (_c *Mockservice_List_Call) Run(run func(ctx context.Context, search string, page int, limit int)) *Mockservice_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *Mockservice_List_Call) Return(_a0 []string, _a1 int, _a2 error) *Mockservice_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Mockservice_List_Call) RunAndReturn(run func(context.Context, string, int, int) ([]string, int, error)) *Mockservice_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, oldName, newName
func (_m *Mockservice) Update(ctx context.Context, oldName string, newName string) error {
	ret := _m.Called(ctx, oldName, newName)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, oldName, newName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mockservice_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Mockservice_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - oldName string
//   - newName string
func (_e *Mockservice_Expecter) Update(ctx interface{}, oldName interface{}, newName interface{}) *Mockservice_Update_Call {
	return &Mockservice_Update_Call{Call: _e.mock.On("Update", ctx, oldName, newName)}
}

func (_c *Mockservice_Update_Call) Run(run func(ctx context.Context, oldName string, newName string)) *Mockservice_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Mockservice_Update_Call) Return(_a0 error) *Mockservice_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mockservice_Update_Call) RunAndReturn(run func(context.Context, string, string) error) *Mockservice_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockservice creates a new instance of Mockservice. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockservice(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockservice {
	mock := &Mockservice{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
