// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "webby/internal/models"
)

// MockLister is an autogenerated mock type for the Lister type
type MockLister struct {
	mock.Mock
}

type MockLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLister) EXPECT() *MockLister_Expecter {
	return &MockLister_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: ctx, search, page, limit
func (_m *MockLister) List(ctx context.Context, search string, page int, limit int) ([]models.Category, int64, error) {
	ret := _m.Called(ctx, search, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Category
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]models.Category, int64, error)); ok {
		return rf(ctx, search, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []models.Category); ok {
		r0 = rf(ctx, search, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int64); ok {
		r1 = rf(ctx, search, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, search, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockLister_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockLister_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - search string
//   - page int
//   - limit int
func (_e *MockLister_Expecter) List(ctx interface{}, search interface{}, page interface{}, limit interface{}) *MockLister_List_Call {
	return &MockLister_List_Call{Call: _e.mock.On("List", ctx, search, page, limit)}
}

func (_c *MockLister_List_Call) Run(run func(ctx context.Context, search string, page int, limit int)) *MockLister_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockLister_List_Call) Return(_a0 []models.Category, _a1 int64, _a2 error) *MockLister_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockLister_List_Call) RunAndReturn(run func(context.Context, string, int, int) ([]models.Category, int64, error)) *MockLister_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLister creates a new instance of MockLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLister {
	mock := &MockLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
