// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	models "webby/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAdder is an autogenerated mock type for the Adder type
type MockAdder struct {
	mock.Mock
}

type MockAdder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdder) EXPECT() *MockAdder_Expecter {
	return &MockAdder_Expecter{mock: &_m.Mock}
}

// AddToQueue provides a mock function with given fields: ctx, roomId, userId, entityId, entityType
func (_m *MockAdder) AddToQueue(ctx context.Context, roomId uuid.UUID, userId uuid.UUID, entityId uuid.UUID, entityType string) (*models.QueueItem, error) {
	ret := _m.Called(ctx, roomId, userId, entityId, entityType)

	if len(ret) == 0 {
		panic("no return value specified for AddToQueue")
	}

	var r0 *models.QueueItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, string) (*models.QueueItem, error)); ok {
		return rf(ctx, roomId, userId, entityId, entityType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, string) *models.QueueItem); ok {
		r0 = rf(ctx, roomId, userId, entityId, entityType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.QueueItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, roomId, userId, entityId, entityType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdder_AddToQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToQueue'
type MockAdder_AddToQueue_Call struct {
	*mock.Call
}

// AddToQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - roomId uuid.UUID
//   - userId uuid.UUID
//   - entityId uuid.UUID
//   - entityType string
func (_e *MockAdder_Expecter) AddToQueue(ctx interface{}, roomId interface{}, userId interface{}, entityId interface{}, entityType interface{}) *MockAdder_AddToQueue_Call {
	return &MockAdder_AddToQueue_Call{Call: _e.mock.On("AddToQueue", ctx, roomId, userId, entityId, entityType)}
}

func (_c *MockAdder_AddToQueue_Call) Run(run func(ctx context.Context, roomId uuid.UUID, userId uuid.UUID, entityId uuid.UUID, entityType string)) *MockAdder_AddToQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID), args[4].(string))
	})
	return _c
}

func (_c *MockAdder_AddToQueue_Call) Return(_a0 *models.QueueItem, _a1 error) *MockAdder_AddToQueue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdder_AddToQueue_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, string) (*models.QueueItem, error)) *MockAdder_AddToQueue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdder creates a new instance of MockAdder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdder {
	mock := &MockAdder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
