services:
  api-gateway:
    build: 
      context: .
      dockerfile: Webby.ApiGetaway/Dockerfile
    ports:
      - "5000:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - JwtOptions__AccessSecretKey=${JwtAccessSecretKey}
      - JwtOptions__AccessExpiresDuration=${JwtAccessExpiresDuration}
    container_name: webby-api-gateway

  auth-service:
    build: 
      context: .
      dockerfile: Webby.AuthService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__AppDbContext=${DatabaseConnectionString}
      - ConnectionStrings__Redis=${RedisDbConnectionString}
      - SenderData__SenderPassword=${SenderPassword}
      - SenderData__SenderEmail=${SenderEmail}
      - JwtOptions__AccessSecretKey=${JwtAccessSecretKey}
      - JwtOptions__AccessExpiresDuration=${JwtAccessExpiresDuration}
      - AutoMapper__LicenseKey=${AutoMapperLicenseKey}
    container_name: webby-auth-service
  
  notification-service:
    build: 
      context: .
      dockerfile: Webby.NotificationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__AppDbContext=${DatabaseConnectionString}
      - JwtOptions__AccessSecretKey=${JwtAccessSecretKey}
      - JwtOptions__AccessExpiresDuration=${JwtAccessExpiresDuration}
      - GrpcClients__UserServiceUrl=${UserGrpcServiceUrl}
    container_name: webby-notification-service
    
  user-service: 
    build: 
      context: .
      dockerfile: Webby.UserService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__AppDbContext=${DatabaseConnectionString}
      - ConnectionStrings__Redis=${RedisPassword}
      - AwsOptions__AccessKey=${AwsAccessKey}
      - AwsOptions__SecretKey=${AwsSecretKey}
      - AwsOptions__BucketName=${AwsBucketName}
      - AwsOptions__Region=${AwsRegion}
      - PaymentOptions__PaymentPublicKey=${StripePublishableKey}
      - PaymentOptions__PaymentSecretKey=${StripeSecretKey}
      - PaymentOptions__PaymentWebhookKey=${StripeWebhookKey}
      - PaymentOptions__SuccessUrl=${PaymentSuccessUrl}
      - PaymentOptions__CancelUrl=${PaymentCancelUrl}
      - AutoMapper__LicenseKey=${AutoMapperLicenseKey}
      - GrpcClients__VideoServiceUrl=${VideoGrpcServiceUrl}
      - GrpcClients__NotificationServiceUrl=${NotificationGrpcServiceUrl}
      - GrpcClients__AchievementServiceUrl=${AchievementGrpcServiceUrl}
    depends_on:
      - redis
    container_name: webby-user-service

  video-service:
    build: 
      context: .
      dockerfile: Webby.VideoService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__AppDbContext=${DatabaseConnectionString}
      - ConnectionStrings__Redis=${RedisDbConnectionString}
      - AwsOptions__AccessKey=${AwsAccessKey}
      - AwsOptions__SecretKey=${AwsSecretKey}
      - AwsOptions__BucketName=${AwsBucketName}
      - AwsOptions__Region=${AwsRegion}
      - ExternalServices__YoutubeOptions__ApiKey=${YouTubeApiKey}
      - ExternalServices__TwitchOptions__ClientId=${TwitchIdClient}
      - ExternalServices__TwitchOptions__ClientSecret=${TwitchSecretKey}
      - ExternalServices__TwitchOptions__ThumbnailWidth=1280
      - ExternalServices__TwitchOptions__ThumbnailHeight=720
      - GrpcClients__UserServiceUrl=${UserGrpcServiceUrl}
    depends_on:
      - redis
    container_name: webby-video-service

  achievement-service:
    build:
      context: . 
      dockerfile:  Webby.AchievementService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__AppDbContext=${DatabaseConnectionString}
      - ConnectionStrings__Redis=${RedisDbConnectionString}
      - AwsOptions__AccessKey=${AwsAccessKey}
      - AwsOptions__SecretKey=${AwsSecretKey}
      - AwsOptions__BucketName=${AwsBucketName}
      - AwsOptions__Region=${AwsRegion}
    depends_on:
      - redis
    container_name: webby-achievement-service

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    container_name: webby-redis
    environment:
      - REDIS_PASSWORD=${RedisPassword}
    command: redis-server --requirepass ${RedisPassword}

  web:
    build:
      context: ../web
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${ServerUrl}
        - NEXT_PUBLIC_SIGNALR_URL=${SignalRUrl}
    container_name: webby-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - AUTH_TRUST_HOST=true
      - NEXT_PUBLIC_API_URL=${ServerUrl}
      - NEXT_PUBLIC_SIGNALR_URL=${SignalRUrl}
      - AUTH_SECRET=${WebAuthSecret}
      - AUTH_GOOGLE_ID=${WebAuthGoogleId}
      - AUTH_GOOGLE_SECRET=${WebGoogleAuthSecret}
      - NEXTAUTH_URL=${NextAuthUrl}
    restart: unless-stopped

  chat-service:
    build:
      context: .
      dockerfile: Webby.ChatService/Dockerfile
    environment:
      - CONNECTION_STRING=${UriConnectionString}
      - JWT_SECRET=${JwtAccessSecretKey}
      - REDIS_ADDR=${RedisAddress}
      - REDIS_PASSWORD=${RedisPassword}
      - HTTP_CHAT_ADDRESS=${HttpChatAddress}
      - GRPC_CHAT_SERVICE_ADDRESS=${ChatGrpcServiceUrl}
      - GRPC_ROOM_SERVICE_ADDRESS=${RoomGrpcServiceUrl}
      - GRPC_USER_SERVICE_ADDRESS=${GoUserGrpcServiceUrl}
    depends_on:
      - redis
    container_name: webby-chat-service

  admin-service:
    build:
      context: .
      dockerfile: Webby.AdminService/Dockerfile
    environment:
      - CONNECTION_STRING=${UriConnectionString}
      - JWT_SECRET=${JwtAccessSecretKey}
      - HTTP_ADMIN_ADDRESS=${HttpAdminAddress}
      - GRPC_MEDIA_SERVICE_ADDRESS=${GoVideoGrpcServiceUrl}
      - GRPC_ROOM_SERVICE_ADDRESS=${RoomGrpcServiceUrl}
      - GRPC_COMPLAINT_SERVICE_ADDRESS=${GoUserGrpcServiceUrl}
      - GRPC_NOTIFICATION_SERVICE_ADDRESS=${GoNotificationGrpcServiceUrl}
    container_name: webby-admin-service

  room-service:
    build:
      context: .
      dockerfile: Webby.RoomService/Dockerfile
    environment:
      - CONNECTION_STRING=${UriConnectionString}
      - JWT_SECRET=${JwtAccessSecretKey}
      - REDIS_ADDR=${RedisAddress}
      - REDIS_PASSWORD=${RedisPassword}
      - AWS_ACCESS_KEY=${AwsAccessKey}
      - AWS_SECRET_KEY=${AwsSecretKey}
      - AWS_BUCKET=${AwsBucketName}
      - AWS_REGION=${AwsRegion}
      - HTTP_ROOM_ADDRESS=${HttpRoomAddress}
      - GRPC_ROOM_SERVICE_ADDRESS=${RoomGrpcServiceUrl}
      - GRPC_MEDIA_SERVICE_ADDRESS=${GoRoomGrpcServiceUrl}
      - GRPC_CHAT_SERVICE_ADDRESS=${GoUserGrpcServiceUrl}
      - GRPC_ROOM_CATEGORY_SERVICE_ADDRESS=${RoomCategoryGrpcServiceUrl}
      - GRPC_ROOM_QUEUE_SERVICE_ADDRESS=${RoomQueueGrpcServiceUrl}
      - GRPC_NOTIFICATION_SERVICE_ADDRESS=${GoNotificationGrpcServiceUrl}
    depends_on:
      - redis
    container_name: webby-room-service

  room-category-service:
    build:
      context: .
      dockerfile: Webby.RoomCategoryService/Dockerfile
    environment:
      - CONNECTION_STRING=${UriConnectionString}
      - JWT_SECRET=${JwtAccessSecretKey}
      - HTTP_ROOM_CATEGORY_ADDRESS=${HttpRoomCategoryAddress}
      - GRPC_ROOM_CATEGORY_SERVICE_ADDRESS=${RoomCategoryGrpcServiceUrl}
    container_name: webby-room-category-service

  room-queue-service:
    build:
      context: .
      dockerfile: Webby.RoomQueueService/Dockerfile
    environment:
      - CONNECTION_STRING=${UriConnectionString}
      - JWT_SECRET=${JwtAccessSecretKey}
      - REDIS_ADDR=${RedisAddress}
      - REDIS_PASSWORD=${RedisPassword}
      - HTTP_ROOM_QUEUE_ADDRESS=${HttpRoomQueueAddress}
      - GRPC_ROOM_QUEUE_SERVICE_ADDRESS=${RoomQueueGrpcServiceUrl}
      - GRPC_MEDIA_SERVICE_ADDRESS=${GoVideoGrpcServiceUrl}
      - GRPC_CHAT_SERVICE_ADDRESS=${ChatGrpcServiceUrl}
      - GRPC_ROOM_SERVICE_ADDRESS=${RoomGrpcServiceUrl}
    depends_on:
      - redis
    container_name: webby-room-queue-service

  votes-service:
    build:
      context: .
      dockerfile: Webby.VotesService/Dockerfile
    environment:
      - CONNECTION_STRING=${UriConnectionString}
      - JWT_SECRET=${JwtAccessSecretKey}
      - REDIS_ADDR=${RedisAddress}
      - REDIS_PASSWORD=${RedisPassword}
      - HTTP_VOTES_ADDRESS=${HttpVotesAddress}
      - GRPC_ROOM_SERVICE_ADDRESS=${RoomGrpcServiceUrl}
      - GRPC_ROOM_QUEUE_SERVICE_ADDRESS=${RoomQueueGrpcServiceUrl}
      - GRPC_CHAT_SERVICE_ADDRESS=${ChatGrpcServiceUrl}
    depends_on:
      - redis
    container_name: webby-votes-service

  ws-gateway:
    build:
      context: .
      dockerfile: Webby.WsGateway/Dockerfile
    environment:
      - CONNECTION_STRING=${UriConnectionString}
      - JWT_SECRET=${JwtAccessSecretKey}
      - REDIS_ADDR=${RedisAddress}
      - REDIS_PASSWORD=${RedisPassword}
      - REDIS_PATTERN=*:*
      - REDIS_DB:0
      - HTTP_WSGATEWAY_ADDRESS=${HttpWsGatewayAddress}
      - GRPC_CHAT_SERVICE_ADDRESS=${ChatGrpcServiceUrl}
      - TOKEN_TTL=5m
    depends_on:
      - redis
    container_name: webby-ws-gateway

volumes:
  redis-data: