version: "3"

tasks:
  run_auth_service:
    desc: "Run the C# AuthService"
    cmds:
      - |
        cd ./Webby.AuthService
        dotnet run

  run_user_service:
    desc: "Run the C# UserService"
    cmds:
      - |
        cd ./Webby.UserService
        dotnet run

  run_video_service:
    desc: "Run the C# VideoService"
    cmds:
      - |
        cd ./Webby.VideoService
        dotnet run

  run_api_getaway:
    desc: "Run the api getaway"
    cmds:
      - |
        cd ./Webby.ApiGetaway
        dotnet run

  run_room_service:
    desc: "Run the Go RoomService"
    cmds:
      - |
        cd ./Webby.RoomService
        CGO_ENABLED=0 go build -o server.exe ./cmd/server/main.go
        ./server.exe --config ./config/config.yaml

  run_chat_service:
    desc: "Run the Go ChatService"
    cmds:
      - |
        cd ./Webby.ChatService
        CGO_ENABLED=0 go build -o server.exe ./cmd/server/main.go
        ./server.exe --config ./config/config.yaml

  run_all:
    desc: "Run all services"
    deps:
      - run_auth_service
      - run_api_getaway
      - run_user_service
      - run_video_service
      - run_room_service
      - run_chat_service
