version: '3'

tasks:
  run_auth_service:
    desc: "Run the C# AuthService"
    cmds:
      - |
        cd ./Webby.AuthService
        dotnet run
  
  run_user_service:
    desc: "Run the C# UserService"
    cmds:
      - |
        cd ./Webby.UserService
        dotnet run

  run_video_service:
    desc: "Run the C# VideoService"
    cmds:
      - |
        cd ./Webby.VideoService
        dotnet run 

  run_api_getaway:
    desc: "Run the api getaway"
    cmds:
      - |
        cd ./Webby.ApiGetaway
        dotnet run
  
  run_all:
    desc: "Run all services"
    deps:
      - run_auth_service
      - run_api_getaway
      - run_user_service
      - run_video_service