// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDeleter is an autogenerated mock type for the Deleter type
type MockDeleter struct {
	mock.Mock
}

type MockDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleter) EXPECT() *MockDeleter_Expecter {
	return &MockDeleter_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, name
func (_m *MockDeleter) Delete(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeleter_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDeleter_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockDeleter_Expecter) Delete(ctx interface{}, name interface{}) *MockDeleter_Delete_Call {
	return &MockDeleter_Delete_Call{Call: _e.mock.On("Delete", ctx, name)}
}

func (_c *MockDeleter_Delete_Call) Run(run func(ctx context.Context, name string)) *MockDeleter_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDeleter_Delete_Call) Return(_a0 error) *MockDeleter_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeleter_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockDeleter_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeleter creates a new instance of MockDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeleter {
	mock := &MockDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
