env: "local"
connectionString: "postgres://postgres.beixuhwayyogudlsimri:Vo%237m8k%2Bw861@aws-1-eu-west-1.pooler.supabase.com:6543/webby?sslmode=disable&pool_max_conns=5"
jwtSecret: "MyExtraMegaSuperKeyThatYouCanUnderstand"
http:
  host: "localhost"
  port: 8081
  timeout: 10s
grpc:
  port: 50051
