// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockSynchronizeService is an autogenerated mock type for the SynchronizeService type
type MockSynchronizeService struct {
	mock.Mock
}

type MockSynchronizeService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSynchronizeService) EXPECT() *MockSynchronizeService_Expecter {
	return &MockSynchronizeService_Expecter{mock: &_m.Mock}
}

// ReportTimecode provides a mock function with given fields: ctx, userID, roomID, syncID, timecode
func (_m *MockSynchronizeService) ReportTimecode(ctx context.Context, userID uuid.UUID, roomID uuid.UUID, syncID uuid.UUID, timecode int) error {
	ret := _m.Called(ctx, userID, roomID, syncID, timecode)

	if len(ret) == 0 {
		panic("no return value specified for ReportTimecode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, int) error); ok {
		r0 = rf(ctx, userID, roomID, syncID, timecode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSynchronizeService_ReportTimecode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportTimecode'
type MockSynchronizeService_ReportTimecode_Call struct {
	*mock.Call
}

// ReportTimecode is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - roomID uuid.UUID
//   - syncID uuid.UUID
//   - timecode int
func (_e *MockSynchronizeService_Expecter) ReportTimecode(ctx interface{}, userID interface{}, roomID interface{}, syncID interface{}, timecode interface{}) *MockSynchronizeService_ReportTimecode_Call {
	return &MockSynchronizeService_ReportTimecode_Call{Call: _e.mock.On("ReportTimecode", ctx, userID, roomID, syncID, timecode)}
}

func (_c *MockSynchronizeService_ReportTimecode_Call) Run(run func(ctx context.Context, userID uuid.UUID, roomID uuid.UUID, syncID uuid.UUID, timecode int)) *MockSynchronizeService_ReportTimecode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID), args[4].(int))
	})
	return _c
}

func (_c *MockSynchronizeService_ReportTimecode_Call) Return(_a0 error) *MockSynchronizeService_ReportTimecode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSynchronizeService_ReportTimecode_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, int) error) *MockSynchronizeService_ReportTimecode_Call {
	_c.Call.Return(run)
	return _c
}

// Synchronize provides a mock function with given fields: ctx, userID, roomID
func (_m *MockSynchronizeService) Synchronize(ctx context.Context, userID uuid.UUID, roomID uuid.UUID) error {
	ret := _m.Called(ctx, userID, roomID)

	if len(ret) == 0 {
		panic("no return value specified for Synchronize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, roomID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSynchronizeService_Synchronize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Synchronize'
type MockSynchronizeService_Synchronize_Call struct {
	*mock.Call
}

// Synchronize is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - roomID uuid.UUID
func (_e *MockSynchronizeService_Expecter) Synchronize(ctx interface{}, userID interface{}, roomID interface{}) *MockSynchronizeService_Synchronize_Call {
	return &MockSynchronizeService_Synchronize_Call{Call: _e.mock.On("Synchronize", ctx, userID, roomID)}
}

func (_c *MockSynchronizeService_Synchronize_Call) Run(run func(ctx context.Context, userID uuid.UUID, roomID uuid.UUID)) *MockSynchronizeService_Synchronize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockSynchronizeService_Synchronize_Call) Return(_a0 error) *MockSynchronizeService_Synchronize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSynchronizeService_Synchronize_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockSynchronizeService_Synchronize_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSynchronizeService creates a new instance of MockSynchronizeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSynchronizeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSynchronizeService {
	mock := &MockSynchronizeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
