// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "webby/room-service/internal/models"

	uuid "github.com/google/uuid"
)

// MockroomMemberService is an autogenerated mock type for the roomMemberService type
type MockroomMemberService struct {
	mock.Mock
}

type MockroomMemberService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockroomMemberService) EXPECT() *MockroomMemberService_Expecter {
	return &MockroomMemberService_Expecter{mock: &_m.Mock}
}

// AddMembers provides a mock function with given fields: ctx, roomID, hostID, memberIDs
func (_m *MockroomMemberService) AddMembers(ctx context.Context, roomID uuid.UUID, hostID uuid.UUID, memberIDs []uuid.UUID) error {
	ret := _m.Called(ctx, roomID, hostID, memberIDs)

	if len(ret) == 0 {
		panic("no return value specified for AddMembers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, []uuid.UUID) error); ok {
		r0 = rf(ctx, roomID, hostID, memberIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockroomMemberService_AddMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMembers'
type MockroomMemberService_AddMembers_Call struct {
	*mock.Call
}

// AddMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - hostID uuid.UUID
//   - memberIDs []uuid.UUID
func (_e *MockroomMemberService_Expecter) AddMembers(ctx interface{}, roomID interface{}, hostID interface{}, memberIDs interface{}) *MockroomMemberService_AddMembers_Call {
	return &MockroomMemberService_AddMembers_Call{Call: _e.mock.On("AddMembers", ctx, roomID, hostID, memberIDs)}
}

func (_c *MockroomMemberService_AddMembers_Call) Run(run func(ctx context.Context, roomID uuid.UUID, hostID uuid.UUID, memberIDs []uuid.UUID)) *MockroomMemberService_AddMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].([]uuid.UUID))
	})
	return _c
}

func (_c *MockroomMemberService_AddMembers_Call) Return(_a0 error) *MockroomMemberService_AddMembers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockroomMemberService_AddMembers_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, []uuid.UUID) error) *MockroomMemberService_AddMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetMemberPoints provides a mock function with given fields: ctx, roomID, userID
func (_m *MockroomMemberService) GetMemberPoints(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberPoints")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (int, error)); ok {
		return rf(ctx, roomID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) int); ok {
		r0 = rf(ctx, roomID, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, roomID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockroomMemberService_GetMemberPoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMemberPoints'
type MockroomMemberService_GetMemberPoints_Call struct {
	*mock.Call
}

// GetMemberPoints is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
func (_e *MockroomMemberService_Expecter) GetMemberPoints(ctx interface{}, roomID interface{}, userID interface{}) *MockroomMemberService_GetMemberPoints_Call {
	return &MockroomMemberService_GetMemberPoints_Call{Call: _e.mock.On("GetMemberPoints", ctx, roomID, userID)}
}

func (_c *MockroomMemberService_GetMemberPoints_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID)) *MockroomMemberService_GetMemberPoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockroomMemberService_GetMemberPoints_Call) Return(_a0 int, _a1 error) *MockroomMemberService_GetMemberPoints_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockroomMemberService_GetMemberPoints_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (int, error)) *MockroomMemberService_GetMemberPoints_Call {
	_c.Call.Return(run)
	return _c
}

// ListMembers provides a mock function with given fields: ctx, roomID, page, limit, search
func (_m *MockroomMemberService) ListMembers(ctx context.Context, roomID uuid.UUID, page int, limit int, search string) ([]models.RoomMemberInfo, int64, error) {
	ret := _m.Called(ctx, roomID, page, limit, search)

	if len(ret) == 0 {
		panic("no return value specified for ListMembers")
	}

	var r0 []models.RoomMemberInfo
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int, string) ([]models.RoomMemberInfo, int64, error)); ok {
		return rf(ctx, roomID, page, limit, search)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int, string) []models.RoomMemberInfo); ok {
		r0 = rf(ctx, roomID, page, limit, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.RoomMemberInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int, string) int64); ok {
		r1 = rf(ctx, roomID, page, limit, search)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int, string) error); ok {
		r2 = rf(ctx, roomID, page, limit, search)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockroomMemberService_ListMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMembers'
type MockroomMemberService_ListMembers_Call struct {
	*mock.Call
}

// ListMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - page int
//   - limit int
//   - search string
func (_e *MockroomMemberService_Expecter) ListMembers(ctx interface{}, roomID interface{}, page interface{}, limit interface{}, search interface{}) *MockroomMemberService_ListMembers_Call {
	return &MockroomMemberService_ListMembers_Call{Call: _e.mock.On("ListMembers", ctx, roomID, page, limit, search)}
}

func (_c *MockroomMemberService_ListMembers_Call) Run(run func(ctx context.Context, roomID uuid.UUID, page int, limit int, search string)) *MockroomMemberService_ListMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int), args[4].(string))
	})
	return _c
}

func (_c *MockroomMemberService_ListMembers_Call) Return(_a0 []models.RoomMemberInfo, _a1 int64, _a2 error) *MockroomMemberService_ListMembers_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockroomMemberService_ListMembers_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int, string) ([]models.RoomMemberInfo, int64, error)) *MockroomMemberService_ListMembers_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function with given fields: ctx, roomID, memberID, hostID
func (_m *MockroomMemberService) RemoveMember(ctx context.Context, roomID uuid.UUID, memberID uuid.UUID, hostID uuid.UUID) error {
	ret := _m.Called(ctx, roomID, memberID, hostID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, roomID, memberID, hostID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockroomMemberService_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type MockroomMemberService_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - memberID uuid.UUID
//   - hostID uuid.UUID
func (_e *MockroomMemberService_Expecter) RemoveMember(ctx interface{}, roomID interface{}, memberID interface{}, hostID interface{}) *MockroomMemberService_RemoveMember_Call {
	return &MockroomMemberService_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, roomID, memberID, hostID)}
}

func (_c *MockroomMemberService_RemoveMember_Call) Run(run func(ctx context.Context, roomID uuid.UUID, memberID uuid.UUID, hostID uuid.UUID)) *MockroomMemberService_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockroomMemberService_RemoveMember_Call) Return(_a0 error) *MockroomMemberService_RemoveMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockroomMemberService_RemoveMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) *MockroomMemberService_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockroomMemberService creates a new instance of MockroomMemberService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockroomMemberService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockroomMemberService {
	mock := &MockroomMemberService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
