// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockPlaybackSynchronizer is an autogenerated mock type for the PlaybackSynchronizer type
type MockPlaybackSynchronizer struct {
	mock.Mock
}

type MockPlaybackSynchronizer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlaybackSynchronizer) EXPECT() *MockPlaybackSynchronizer_Expecter {
	return &MockPlaybackSynchronizer_Expecter{mock: &_m.Mock}
}

// ExecuteReportTimecode provides a mock function with given fields: ctx, userID, roomID, syncID, timecode
func (_m *MockPlaybackSynchronizer) ExecuteReportTimecode(ctx context.Context, userID uuid.UUID, roomID uuid.UUID, syncID uuid.UUID, timecode int) error {
	ret := _m.Called(ctx, userID, roomID, syncID, timecode)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteReportTimecode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, int) error); ok {
		r0 = rf(ctx, userID, roomID, syncID, timecode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPlaybackSynchronizer_ExecuteReportTimecode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteReportTimecode'
type MockPlaybackSynchronizer_ExecuteReportTimecode_Call struct {
	*mock.Call
}

// ExecuteReportTimecode is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - roomID uuid.UUID
//   - syncID uuid.UUID
//   - timecode int
func (_e *MockPlaybackSynchronizer_Expecter) ExecuteReportTimecode(ctx interface{}, userID interface{}, roomID interface{}, syncID interface{}, timecode interface{}) *MockPlaybackSynchronizer_ExecuteReportTimecode_Call {
	return &MockPlaybackSynchronizer_ExecuteReportTimecode_Call{Call: _e.mock.On("ExecuteReportTimecode", ctx, userID, roomID, syncID, timecode)}
}

func (_c *MockPlaybackSynchronizer_ExecuteReportTimecode_Call) Run(run func(ctx context.Context, userID uuid.UUID, roomID uuid.UUID, syncID uuid.UUID, timecode int)) *MockPlaybackSynchronizer_ExecuteReportTimecode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID), args[4].(int))
	})
	return _c
}

func (_c *MockPlaybackSynchronizer_ExecuteReportTimecode_Call) Return(_a0 error) *MockPlaybackSynchronizer_ExecuteReportTimecode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlaybackSynchronizer_ExecuteReportTimecode_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, int) error) *MockPlaybackSynchronizer_ExecuteReportTimecode_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteSynchronize provides a mock function with given fields: ctx, userID, roomID
func (_m *MockPlaybackSynchronizer) ExecuteSynchronize(ctx context.Context, userID uuid.UUID, roomID uuid.UUID) error {
	ret := _m.Called(ctx, userID, roomID)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteSynchronize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, roomID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPlaybackSynchronizer_ExecuteSynchronize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteSynchronize'
type MockPlaybackSynchronizer_ExecuteSynchronize_Call struct {
	*mock.Call
}

// ExecuteSynchronize is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - roomID uuid.UUID
func (_e *MockPlaybackSynchronizer_Expecter) ExecuteSynchronize(ctx interface{}, userID interface{}, roomID interface{}) *MockPlaybackSynchronizer_ExecuteSynchronize_Call {
	return &MockPlaybackSynchronizer_ExecuteSynchronize_Call{Call: _e.mock.On("ExecuteSynchronize", ctx, userID, roomID)}
}

func (_c *MockPlaybackSynchronizer_ExecuteSynchronize_Call) Run(run func(ctx context.Context, userID uuid.UUID, roomID uuid.UUID)) *MockPlaybackSynchronizer_ExecuteSynchronize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockPlaybackSynchronizer_ExecuteSynchronize_Call) Return(_a0 error) *MockPlaybackSynchronizer_ExecuteSynchronize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlaybackSynchronizer_ExecuteSynchronize_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockPlaybackSynchronizer_ExecuteSynchronize_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPlaybackSynchronizer creates a new instance of MockPlaybackSynchronizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlaybackSynchronizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlaybackSynchronizer {
	mock := &MockPlaybackSynchronizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
