// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "webby/room-service/internal/models"

	uuid "github.com/google/uuid"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AddMembers provides a mock function with given fields: ctx, roomID, userID, memberIDs
func (_m *MockService) AddMembers(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, memberIDs []uuid.UUID) error {
	ret := _m.Called(ctx, roomID, userID, memberIDs)

	if len(ret) == 0 {
		panic("no return value specified for AddMembers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, []uuid.UUID) error); ok {
		r0 = rf(ctx, roomID, userID, memberIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_AddMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMembers'
type MockService_AddMembers_Call struct {
	*mock.Call
}

// AddMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
//   - memberIDs []uuid.UUID
func (_e *MockService_Expecter) AddMembers(ctx interface{}, roomID interface{}, userID interface{}, memberIDs interface{}) *MockService_AddMembers_Call {
	return &MockService_AddMembers_Call{Call: _e.mock.On("AddMembers", ctx, roomID, userID, memberIDs)}
}

func (_c *MockService_AddMembers_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, memberIDs []uuid.UUID)) *MockService_AddMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].([]uuid.UUID))
	})
	return _c
}

func (_c *MockService_AddMembers_Call) Return(_a0 error) *MockService_AddMembers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_AddMembers_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, []uuid.UUID) error) *MockService_AddMembers_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, room, thumbnailData, thumbnailFilename
func (_m *MockService) Create(ctx context.Context, room *models.Room, thumbnailData []byte, thumbnailFilename string) (*models.Room, error) {
	ret := _m.Called(ctx, room, thumbnailData, thumbnailFilename)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Room, []byte, string) (*models.Room, error)); ok {
		return rf(ctx, room, thumbnailData, thumbnailFilename)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Room, []byte, string) *models.Room); ok {
		r0 = rf(ctx, room, thumbnailData, thumbnailFilename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Room, []byte, string) error); ok {
		r1 = rf(ctx, room, thumbnailData, thumbnailFilename)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - room *models.Room
//   - thumbnailData []byte
//   - thumbnailFilename string
func (_e *MockService_Expecter) Create(ctx interface{}, room interface{}, thumbnailData interface{}, thumbnailFilename interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, room, thumbnailData, thumbnailFilename)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, room *models.Room, thumbnailData []byte, thumbnailFilename string)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Room), args[2].([]byte), args[3].(string))
	})
	return _c
}

func (_c *MockService_Create_Call) Return(_a0 *models.Room, _a1 error) *MockService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(context.Context, *models.Room, []byte, string) (*models.Room, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id, userID
func (_m *MockService) Delete(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) Delete(ctx interface{}, id interface{}, userID interface{}) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", ctx, id, userID)}
}

func (_c *MockService_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(_a0 error) *MockService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, roomID, userID
func (_m *MockService) GetByID(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) (*models.Room, error) {
	ret := _m.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.Room, error)); ok {
		return rf(ctx, roomID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.Room); ok {
		r0 = rf(ctx, roomID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, roomID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) GetByID(ctx interface{}, roomID interface{}, userID interface{}) *MockService_GetByID_Call {
	return &MockService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, roomID, userID)}
}

func (_c *MockService_GetByID_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID)) *MockService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_GetByID_Call) Return(_a0 *models.Room, _a1 error) *MockService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*models.Room, error)) *MockService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListMembers provides a mock function with given fields: ctx, roomID, page, limit, search
func (_m *MockService) ListMembers(ctx context.Context, roomID uuid.UUID, page int, limit int, search string) ([]models.RoomMemberInfo, int64, error) {
	ret := _m.Called(ctx, roomID, page, limit, search)

	if len(ret) == 0 {
		panic("no return value specified for ListMembers")
	}

	var r0 []models.RoomMemberInfo
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int, string) ([]models.RoomMemberInfo, int64, error)); ok {
		return rf(ctx, roomID, page, limit, search)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int, string) []models.RoomMemberInfo); ok {
		r0 = rf(ctx, roomID, page, limit, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.RoomMemberInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int, string) int64); ok {
		r1 = rf(ctx, roomID, page, limit, search)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int, string) error); ok {
		r2 = rf(ctx, roomID, page, limit, search)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockService_ListMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMembers'
type MockService_ListMembers_Call struct {
	*mock.Call
}

// ListMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - page int
//   - limit int
//   - search string
func (_e *MockService_Expecter) ListMembers(ctx interface{}, roomID interface{}, page interface{}, limit interface{}, search interface{}) *MockService_ListMembers_Call {
	return &MockService_ListMembers_Call{Call: _e.mock.On("ListMembers", ctx, roomID, page, limit, search)}
}

func (_c *MockService_ListMembers_Call) Run(run func(ctx context.Context, roomID uuid.UUID, page int, limit int, search string)) *MockService_ListMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int), args[4].(string))
	})
	return _c
}

func (_c *MockService_ListMembers_Call) Return(_a0 []models.RoomMemberInfo, _a1 int64, _a2 error) *MockService_ListMembers_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockService_ListMembers_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int, string) ([]models.RoomMemberInfo, int64, error)) *MockService_ListMembers_Call {
	_c.Call.Return(run)
	return _c
}

// ListMy provides a mock function with given fields: ctx, userID, page, limit, search, category
func (_m *MockService) ListMy(ctx context.Context, userID uuid.UUID, page int, limit int, search string, category string) ([]models.Room, int64, error) {
	ret := _m.Called(ctx, userID, page, limit, search, category)

	if len(ret) == 0 {
		panic("no return value specified for ListMy")
	}

	var r0 []models.Room
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int, string, string) ([]models.Room, int64, error)); ok {
		return rf(ctx, userID, page, limit, search, category)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int, string, string) []models.Room); ok {
		r0 = rf(ctx, userID, page, limit, search, category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int, string, string) int64); ok {
		r1 = rf(ctx, userID, page, limit, search, category)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int, string, string) error); ok {
		r2 = rf(ctx, userID, page, limit, search, category)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockService_ListMy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMy'
type MockService_ListMy_Call struct {
	*mock.Call
}

// ListMy is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - page int
//   - limit int
//   - search string
//   - category string
func (_e *MockService_Expecter) ListMy(ctx interface{}, userID interface{}, page interface{}, limit interface{}, search interface{}, category interface{}) *MockService_ListMy_Call {
	return &MockService_ListMy_Call{Call: _e.mock.On("ListMy", ctx, userID, page, limit, search, category)}
}

func (_c *MockService_ListMy_Call) Run(run func(ctx context.Context, userID uuid.UUID, page int, limit int, search string, category string)) *MockService_ListMy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *MockService_ListMy_Call) Return(_a0 []models.Room, _a1 int64, _a2 error) *MockService_ListMy_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockService_ListMy_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int, string, string) ([]models.Room, int64, error)) *MockService_ListMy_Call {
	_c.Call.Return(run)
	return _c
}

// ListPublic provides a mock function with given fields: ctx, page, limit, search, category
func (_m *MockService) ListPublic(ctx context.Context, page int, limit int, search string, category string) ([]models.PublicRoom, int64, error) {
	ret := _m.Called(ctx, page, limit, search, category)

	if len(ret) == 0 {
		panic("no return value specified for ListPublic")
	}

	var r0 []models.PublicRoom
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string) ([]models.PublicRoom, int64, error)); ok {
		return rf(ctx, page, limit, search, category)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string) []models.PublicRoom); ok {
		r0 = rf(ctx, page, limit, search, category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PublicRoom)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string) int64); ok {
		r1 = rf(ctx, page, limit, search, category)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string, string) error); ok {
		r2 = rf(ctx, page, limit, search, category)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockService_ListPublic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPublic'
type MockService_ListPublic_Call struct {
	*mock.Call
}

// ListPublic is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - limit int
//   - search string
//   - category string
func (_e *MockService_Expecter) ListPublic(ctx interface{}, page interface{}, limit interface{}, search interface{}, category interface{}) *MockService_ListPublic_Call {
	return &MockService_ListPublic_Call{Call: _e.mock.On("ListPublic", ctx, page, limit, search, category)}
}

func (_c *MockService_ListPublic_Call) Run(run func(ctx context.Context, page int, limit int, search string, category string)) *MockService_ListPublic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockService_ListPublic_Call) Return(_a0 []models.PublicRoom, _a1 int64, _a2 error) *MockService_ListPublic_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockService_ListPublic_Call) RunAndReturn(run func(context.Context, int, int, string, string) ([]models.PublicRoom, int64, error)) *MockService_ListPublic_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function with given fields: ctx, roomID, memberID, hostID
func (_m *MockService) RemoveMember(ctx context.Context, roomID uuid.UUID, memberID uuid.UUID, hostID uuid.UUID) error {
	ret := _m.Called(ctx, roomID, memberID, hostID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, roomID, memberID, hostID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type MockService_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - memberID uuid.UUID
//   - hostID uuid.UUID
func (_e *MockService_Expecter) RemoveMember(ctx interface{}, roomID interface{}, memberID interface{}, hostID interface{}) *MockService_RemoveMember_Call {
	return &MockService_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, roomID, memberID, hostID)}
}

func (_c *MockService_RemoveMember_Call) Run(run func(ctx context.Context, roomID uuid.UUID, memberID uuid.UUID, hostID uuid.UUID)) *MockService_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_RemoveMember_Call) Return(_a0 error) *MockService_RemoveMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_RemoveMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) *MockService_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// ReportTimecode provides a mock function with given fields: ctx, userID, roomID, syncID, timecode
func (_m *MockService) ReportTimecode(ctx context.Context, userID uuid.UUID, roomID uuid.UUID, syncID uuid.UUID, timecode int) error {
	ret := _m.Called(ctx, userID, roomID, syncID, timecode)

	if len(ret) == 0 {
		panic("no return value specified for ReportTimecode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, int) error); ok {
		r0 = rf(ctx, userID, roomID, syncID, timecode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_ReportTimecode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportTimecode'
type MockService_ReportTimecode_Call struct {
	*mock.Call
}

// ReportTimecode is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - roomID uuid.UUID
//   - syncID uuid.UUID
//   - timecode int
func (_e *MockService_Expecter) ReportTimecode(ctx interface{}, userID interface{}, roomID interface{}, syncID interface{}, timecode interface{}) *MockService_ReportTimecode_Call {
	return &MockService_ReportTimecode_Call{Call: _e.mock.On("ReportTimecode", ctx, userID, roomID, syncID, timecode)}
}

func (_c *MockService_ReportTimecode_Call) Run(run func(ctx context.Context, userID uuid.UUID, roomID uuid.UUID, syncID uuid.UUID, timecode int)) *MockService_ReportTimecode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID), args[4].(int))
	})
	return _c
}

func (_c *MockService_ReportTimecode_Call) Return(_a0 error) *MockService_ReportTimecode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_ReportTimecode_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, int) error) *MockService_ReportTimecode_Call {
	_c.Call.Return(run)
	return _c
}

// Synchronize provides a mock function with given fields: ctx, userID, roomID
func (_m *MockService) Synchronize(ctx context.Context, userID uuid.UUID, roomID uuid.UUID) error {
	ret := _m.Called(ctx, userID, roomID)

	if len(ret) == 0 {
		panic("no return value specified for Synchronize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, roomID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Synchronize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Synchronize'
type MockService_Synchronize_Call struct {
	*mock.Call
}

// Synchronize is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - roomID uuid.UUID
func (_e *MockService_Expecter) Synchronize(ctx interface{}, userID interface{}, roomID interface{}) *MockService_Synchronize_Call {
	return &MockService_Synchronize_Call{Call: _e.mock.On("Synchronize", ctx, userID, roomID)}
}

func (_c *MockService_Synchronize_Call) Run(run func(ctx context.Context, userID uuid.UUID, roomID uuid.UUID)) *MockService_Synchronize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_Synchronize_Call) Return(_a0 error) *MockService_Synchronize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Synchronize_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockService_Synchronize_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, roomID, userID, name, category, thumbnailFilename, thumbnailData, isPrivate
func (_m *MockService) Update(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, name *string, category *string, thumbnailFilename *string, thumbnailData *[]byte, isPrivate *bool) (*models.Room, error) {
	ret := _m.Called(ctx, roomID, userID, name, category, thumbnailFilename, thumbnailData, isPrivate)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *string, *string, *string, *[]byte, *bool) (*models.Room, error)); ok {
		return rf(ctx, roomID, userID, name, category, thumbnailFilename, thumbnailData, isPrivate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *string, *string, *string, *[]byte, *bool) *models.Room); ok {
		r0 = rf(ctx, roomID, userID, name, category, thumbnailFilename, thumbnailData, isPrivate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, *string, *string, *string, *[]byte, *bool) error); ok {
		r1 = rf(ctx, roomID, userID, name, category, thumbnailFilename, thumbnailData, isPrivate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
//   - name *string
//   - category *string
//   - thumbnailFilename *string
//   - thumbnailData *[]byte
//   - isPrivate *bool
func (_e *MockService_Expecter) Update(ctx interface{}, roomID interface{}, userID interface{}, name interface{}, category interface{}, thumbnailFilename interface{}, thumbnailData interface{}, isPrivate interface{}) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", ctx, roomID, userID, name, category, thumbnailFilename, thumbnailData, isPrivate)}
}

func (_c *MockService_Update_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, name *string, category *string, thumbnailFilename *string, thumbnailData *[]byte, isPrivate *bool)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(*string), args[4].(*string), args[5].(*string), args[6].(*[]byte), args[7].(*bool))
	})
	return _c
}

func (_c *MockService_Update_Call) Return(_a0 *models.Room, _a1 error) *MockService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, *string, *string, *string, *[]byte, *bool) (*models.Room, error)) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
