// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: proto/votes/votes.proto

package votespb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VotesGrpcService_CastVote_FullMethodName = "/votes.VotesGrpcService/CastVote"
)

// VotesGrpcServiceClient is the client API for VotesGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VotesGrpcServiceClient interface {
	CastVote(ctx context.Context, in *CastVoteRequest, opts ...grpc.CallOption) (*CastVoteResponse, error)
}

type votesGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVotesGrpcServiceClient(cc grpc.ClientConnInterface) VotesGrpcServiceClient {
	return &votesGrpcServiceClient{cc}
}

func (c *votesGrpcServiceClient) CastVote(ctx context.Context, in *CastVoteRequest, opts ...grpc.CallOption) (*CastVoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CastVoteResponse)
	err := c.cc.Invoke(ctx, VotesGrpcService_CastVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VotesGrpcServiceServer is the server API for VotesGrpcService service.
// All implementations must embed UnimplementedVotesGrpcServiceServer
// for forward compatibility.
type VotesGrpcServiceServer interface {
	CastVote(context.Context, *CastVoteRequest) (*CastVoteResponse, error)
	mustEmbedUnimplementedVotesGrpcServiceServer()
}

// UnimplementedVotesGrpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVotesGrpcServiceServer struct{}

func (UnimplementedVotesGrpcServiceServer) CastVote(context.Context, *CastVoteRequest) (*CastVoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CastVote not implemented")
}
func (UnimplementedVotesGrpcServiceServer) mustEmbedUnimplementedVotesGrpcServiceServer() {}
func (UnimplementedVotesGrpcServiceServer) testEmbeddedByValue()                          {}

// UnsafeVotesGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VotesGrpcServiceServer will
// result in compilation errors.
type UnsafeVotesGrpcServiceServer interface {
	mustEmbedUnimplementedVotesGrpcServiceServer()
}

func RegisterVotesGrpcServiceServer(s grpc.ServiceRegistrar, srv VotesGrpcServiceServer) {
	// If the following call panics, it indicates UnimplementedVotesGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VotesGrpcService_ServiceDesc, srv)
}

func _VotesGrpcService_CastVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CastVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VotesGrpcServiceServer).CastVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VotesGrpcService_CastVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VotesGrpcServiceServer).CastVote(ctx, req.(*CastVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VotesGrpcService_ServiceDesc is the grpc.ServiceDesc for VotesGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VotesGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "votes.VotesGrpcService",
	HandlerType: (*VotesGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CastVote",
			Handler:    _VotesGrpcService_CastVote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/votes/votes.proto",
}
