// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: proto/votes/votes.proto

package votespb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CastVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VoteId        string                 `protobuf:"bytes,3,opt,name=vote_id,json=voteId,proto3" json:"vote_id,omitempty"`
	ChoiceId      string                 `protobuf:"bytes,4,opt,name=choice_id,json=choiceId,proto3" json:"choice_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CastVoteRequest) Reset() {
	*x = CastVoteRequest{}
	mi := &file_proto_votes_votes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastVoteRequest) ProtoMessage() {}

func (x *CastVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_votes_votes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastVoteRequest.ProtoReflect.Descriptor instead.
func (*CastVoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_votes_votes_proto_rawDescGZIP(), []int{0}
}

func (x *CastVoteRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CastVoteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CastVoteRequest) GetVoteId() string {
	if x != nil {
		return x.VoteId
	}
	return ""
}

func (x *CastVoteRequest) GetChoiceId() string {
	if x != nil {
		return x.ChoiceId
	}
	return ""
}

type CastVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CastVoteResponse) Reset() {
	*x = CastVoteResponse{}
	mi := &file_proto_votes_votes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastVoteResponse) ProtoMessage() {}

func (x *CastVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_votes_votes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastVoteResponse.ProtoReflect.Descriptor instead.
func (*CastVoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_votes_votes_proto_rawDescGZIP(), []int{1}
}

var File_proto_votes_votes_proto protoreflect.FileDescriptor

const file_proto_votes_votes_proto_rawDesc = "" +
	"\n" +
	"\x17proto/votes/votes.proto\x12\x05votes\"y\n" +
	"\x0fCastVoteRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\avote_id\x18\x03 \x01(\tR\x06voteId\x12\x1b\n" +
	"\tchoice_id\x18\x04 \x01(\tR\bchoiceId\"\x12\n" +
	"\x10CastVoteResponse2O\n" +
	"\x10VotesGrpcService\x12;\n" +
	"\bCastVote\x12\x16.votes.CastVoteRequest\x1a\x17.votes.CastVoteResponseB'Z%webby/wsgateway/internal/grpc/votespbb\x06proto3"

var (
	file_proto_votes_votes_proto_rawDescOnce sync.Once
	file_proto_votes_votes_proto_rawDescData []byte
)

func file_proto_votes_votes_proto_rawDescGZIP() []byte {
	file_proto_votes_votes_proto_rawDescOnce.Do(func() {
		file_proto_votes_votes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_votes_votes_proto_rawDesc), len(file_proto_votes_votes_proto_rawDesc)))
	})
	return file_proto_votes_votes_proto_rawDescData
}

var file_proto_votes_votes_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_votes_votes_proto_goTypes = []any{
	(*CastVoteRequest)(nil),  // 0: votes.CastVoteRequest
	(*CastVoteResponse)(nil), // 1: votes.CastVoteResponse
}
var file_proto_votes_votes_proto_depIdxs = []int32{
	0, // 0: votes.VotesGrpcService.CastVote:input_type -> votes.CastVoteRequest
	1, // 1: votes.VotesGrpcService.CastVote:output_type -> votes.CastVoteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_votes_votes_proto_init() }
func file_proto_votes_votes_proto_init() {
	if File_proto_votes_votes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_votes_votes_proto_rawDesc), len(file_proto_votes_votes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_votes_votes_proto_goTypes,
		DependencyIndexes: file_proto_votes_votes_proto_depIdxs,
		MessageInfos:      file_proto_votes_votes_proto_msgTypes,
	}.Build()
	File_proto_votes_votes_proto = out.File
	file_proto_votes_votes_proto_goTypes = nil
	file_proto_votes_votes_proto_depIdxs = nil
}
