// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: proto/queue/queue.proto

package queuepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MoveToTopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToTopRequest) Reset() {
	*x = MoveToTopRequest{}
	mi := &file_proto_queue_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToTopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToTopRequest) ProtoMessage() {}

func (x *MoveToTopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToTopRequest.ProtoReflect.Descriptor instead.
func (*MoveToTopRequest) Descriptor() ([]byte, []int) {
	return file_proto_queue_queue_proto_rawDescGZIP(), []int{0}
}

func (x *MoveToTopRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MoveToTopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToTopResponse) Reset() {
	*x = MoveToTopResponse{}
	mi := &file_proto_queue_queue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToTopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToTopResponse) ProtoMessage() {}

func (x *MoveToTopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_queue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToTopResponse.ProtoReflect.Descriptor instead.
func (*MoveToTopResponse) Descriptor() ([]byte, []int) {
	return file_proto_queue_queue_proto_rawDescGZIP(), []int{1}
}

func (x *MoveToTopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_queue_queue_proto protoreflect.FileDescriptor

const file_proto_queue_queue_proto_rawDesc = "" +
	"\n" +
	"\x17proto/queue/queue.proto\x12\x05queue\"\"\n" +
	"\x10MoveToTopRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x11MoveToTopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2R\n" +
	"\x10QueueGrpcService\x12>\n" +
	"\tMoveToTop\x12\x17.queue.MoveToTopRequest\x1a\x18.queue.MoveToTopResponseB0Z.webby/room-queue-service/internal/grpc/queuepbb\x06proto3"

var (
	file_proto_queue_queue_proto_rawDescOnce sync.Once
	file_proto_queue_queue_proto_rawDescData []byte
)

func file_proto_queue_queue_proto_rawDescGZIP() []byte {
	file_proto_queue_queue_proto_rawDescOnce.Do(func() {
		file_proto_queue_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_queue_queue_proto_rawDesc), len(file_proto_queue_queue_proto_rawDesc)))
	})
	return file_proto_queue_queue_proto_rawDescData
}

var file_proto_queue_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_queue_queue_proto_goTypes = []any{
	(*MoveToTopRequest)(nil),  // 0: queue.MoveToTopRequest
	(*MoveToTopResponse)(nil), // 1: queue.MoveToTopResponse
}
var file_proto_queue_queue_proto_depIdxs = []int32{
	0, // 0: queue.QueueGrpcService.MoveToTop:input_type -> queue.MoveToTopRequest
	1, // 1: queue.QueueGrpcService.MoveToTop:output_type -> queue.MoveToTopResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_queue_queue_proto_init() }
func file_proto_queue_queue_proto_init() {
	if File_proto_queue_queue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_queue_queue_proto_rawDesc), len(file_proto_queue_queue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_queue_queue_proto_goTypes,
		DependencyIndexes: file_proto_queue_queue_proto_depIdxs,
		MessageInfos:      file_proto_queue_queue_proto_msgTypes,
	}.Build()
	File_proto_queue_queue_proto = out.File
	file_proto_queue_queue_proto_goTypes = nil
	file_proto_queue_queue_proto_depIdxs = nil
}
