// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "webby/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUpdater is an autogenerated mock type for the Updater type
type MockUpdater struct {
	mock.Mock
}

type MockUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdater) EXPECT() *MockUpdater_Expecter {
	return &MockUpdater_Expecter{mock: &_m.Mock}
}

// Update provides a mock function with given fields: room
func (_m *MockUpdater) Update(room *models.Room) (uuid.UUID, error) {
	ret := _m.Called(room)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.Room) (uuid.UUID, error)); ok {
		return rf(room)
	}
	if rf, ok := ret.Get(0).(func(*models.Room) uuid.UUID); ok {
		r0 = rf(room)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.Room) error); ok {
		r1 = rf(room)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdater_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUpdater_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - room *models.Room
func (_e *MockUpdater_Expecter) Update(room interface{}) *MockUpdater_Update_Call {
	return &MockUpdater_Update_Call{Call: _e.mock.On("Update", room)}
}

func (_c *MockUpdater_Update_Call) Run(run func(room *models.Room)) *MockUpdater_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Room))
	})
	return _c
}

func (_c *MockUpdater_Update_Call) Return(_a0 uuid.UUID, _a1 error) *MockUpdater_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdater_Update_Call) RunAndReturn(run func(*models.Room) (uuid.UUID, error)) *MockUpdater_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdater creates a new instance of MockUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdater {
	mock := &MockUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
