// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	models "webby/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRoomService is an autogenerated mock type for the RoomService type
type MockRoomService struct {
	mock.Mock
}

type MockRoomService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomService) EXPECT() *MockRoomService_Expecter {
	return &MockRoomService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, room, thumbnailData, thumbnailFilename
func (_m *MockRoomService) Create(ctx context.Context, room *models.Room, thumbnailData []byte, thumbnailFilename string) (*models.Room, error) {
	ret := _m.Called(ctx, room, thumbnailData, thumbnailFilename)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Room, []byte, string) (*models.Room, error)); ok {
		return rf(ctx, room, thumbnailData, thumbnailFilename)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Room, []byte, string) *models.Room); ok {
		r0 = rf(ctx, room, thumbnailData, thumbnailFilename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Room, []byte, string) error); ok {
		r1 = rf(ctx, room, thumbnailData, thumbnailFilename)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoomService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - room *models.Room
//   - thumbnailData []byte
//   - thumbnailFilename string
func (_e *MockRoomService_Expecter) Create(ctx interface{}, room interface{}, thumbnailData interface{}, thumbnailFilename interface{}) *MockRoomService_Create_Call {
	return &MockRoomService_Create_Call{Call: _e.mock.On("Create", ctx, room, thumbnailData, thumbnailFilename)}
}

func (_c *MockRoomService_Create_Call) Run(run func(ctx context.Context, room *models.Room, thumbnailData []byte, thumbnailFilename string)) *MockRoomService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Room), args[2].([]byte), args[3].(string))
	})
	return _c
}

func (_c *MockRoomService_Create_Call) Return(_a0 *models.Room, _a1 error) *MockRoomService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomService_Create_Call) RunAndReturn(run func(context.Context, *models.Room, []byte, string) (*models.Room, error)) *MockRoomService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id, userId
func (_m *MockRoomService) Delete(ctx context.Context, id uuid.UUID, userId uuid.UUID) error {
	ret := _m.Called(ctx, id, userId)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, id, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoomService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRoomService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userId uuid.UUID
func (_e *MockRoomService_Expecter) Delete(ctx interface{}, id interface{}, userId interface{}) *MockRoomService_Delete_Call {
	return &MockRoomService_Delete_Call{Call: _e.mock.On("Delete", ctx, id, userId)}
}

func (_c *MockRoomService_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID, userId uuid.UUID)) *MockRoomService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRoomService_Delete_Call) Return(_a0 error) *MockRoomService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoomService_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockRoomService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function with given fields: ctx, roomId, userId
func (_m *MockRoomService) GetById(ctx context.Context, roomId uuid.UUID, userId uuid.UUID) (*models.Room, error) {
	ret := _m.Called(ctx, roomId, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *models.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.Room, error)); ok {
		return rf(ctx, roomId, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.Room); ok {
		r0 = rf(ctx, roomId, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, roomId, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomService_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockRoomService_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - roomId uuid.UUID
//   - userId uuid.UUID
func (_e *MockRoomService_Expecter) GetById(ctx interface{}, roomId interface{}, userId interface{}) *MockRoomService_GetById_Call {
	return &MockRoomService_GetById_Call{Call: _e.mock.On("GetById", ctx, roomId, userId)}
}

func (_c *MockRoomService_GetById_Call) Run(run func(ctx context.Context, roomId uuid.UUID, userId uuid.UUID)) *MockRoomService_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRoomService_GetById_Call) Return(_a0 *models.Room, _a1 error) *MockRoomService_GetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomService_GetById_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*models.Room, error)) *MockRoomService_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetByToken provides a mock function with given fields: ctx, token, userId
func (_m *MockRoomService) GetByToken(ctx context.Context, token string, userId uuid.UUID) (*models.Room, error) {
	ret := _m.Called(ctx, token, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetByToken")
	}

	var r0 *models.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) (*models.Room, error)); ok {
		return rf(ctx, token, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) *models.Room); ok {
		r0 = rf(ctx, token, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(ctx, token, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomService_GetByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByToken'
type MockRoomService_GetByToken_Call struct {
	*mock.Call
}

// GetByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - userId uuid.UUID
func (_e *MockRoomService_Expecter) GetByToken(ctx interface{}, token interface{}, userId interface{}) *MockRoomService_GetByToken_Call {
	return &MockRoomService_GetByToken_Call{Call: _e.mock.On("GetByToken", ctx, token, userId)}
}

func (_c *MockRoomService_GetByToken_Call) Run(run func(ctx context.Context, token string, userId uuid.UUID)) *MockRoomService_GetByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRoomService_GetByToken_Call) Return(_a0 *models.Room, _a1 error) *MockRoomService_GetByToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomService_GetByToken_Call) RunAndReturn(run func(context.Context, string, uuid.UUID) (*models.Room, error)) *MockRoomService_GetByToken_Call {
	_c.Call.Return(run)
	return _c
}

// ListMembers provides a mock function with given fields: roomId, page, limit, search
func (_m *MockRoomService) ListMembers(roomId uuid.UUID, page int, limit int, search string) ([]models.RoomMemberInfo, int64, error) {
	ret := _m.Called(roomId, page, limit, search)

	if len(ret) == 0 {
		panic("no return value specified for ListMembers")
	}

	var r0 []models.RoomMemberInfo
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int, string) ([]models.RoomMemberInfo, int64, error)); ok {
		return rf(roomId, page, limit, search)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int, string) []models.RoomMemberInfo); ok {
		r0 = rf(roomId, page, limit, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.RoomMemberInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, int, int, string) int64); ok {
		r1 = rf(roomId, page, limit, search)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID, int, int, string) error); ok {
		r2 = rf(roomId, page, limit, search)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRoomService_ListMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMembers'
type MockRoomService_ListMembers_Call struct {
	*mock.Call
}

// ListMembers is a helper method to define mock.On call
//   - roomId uuid.UUID
//   - page int
//   - limit int
//   - search string
func (_e *MockRoomService_Expecter) ListMembers(roomId interface{}, page interface{}, limit interface{}, search interface{}) *MockRoomService_ListMembers_Call {
	return &MockRoomService_ListMembers_Call{Call: _e.mock.On("ListMembers", roomId, page, limit, search)}
}

func (_c *MockRoomService_ListMembers_Call) Run(run func(roomId uuid.UUID, page int, limit int, search string)) *MockRoomService_ListMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(int), args[2].(int), args[3].(string))
	})
	return _c
}

func (_c *MockRoomService_ListMembers_Call) Return(_a0 []models.RoomMemberInfo, _a1 int64, _a2 error) *MockRoomService_ListMembers_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRoomService_ListMembers_Call) RunAndReturn(run func(uuid.UUID, int, int, string) ([]models.RoomMemberInfo, int64, error)) *MockRoomService_ListMembers_Call {
	_c.Call.Return(run)
	return _c
}

// ListMy provides a mock function with given fields: id, page, limit
func (_m *MockRoomService) ListMy(id uuid.UUID, page int, limit int) ([]models.Room, int64, error) {
	ret := _m.Called(id, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListMy")
	}

	var r0 []models.Room
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int) ([]models.Room, int64, error)); ok {
		return rf(id, page, limit)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int) []models.Room); ok {
		r0 = rf(id, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, int, int) int64); ok {
		r1 = rf(id, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID, int, int) error); ok {
		r2 = rf(id, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRoomService_ListMy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMy'
type MockRoomService_ListMy_Call struct {
	*mock.Call
}

// ListMy is a helper method to define mock.On call
//   - id uuid.UUID
//   - page int
//   - limit int
func (_e *MockRoomService_Expecter) ListMy(id interface{}, page interface{}, limit interface{}) *MockRoomService_ListMy_Call {
	return &MockRoomService_ListMy_Call{Call: _e.mock.On("ListMy", id, page, limit)}
}

func (_c *MockRoomService_ListMy_Call) Run(run func(id uuid.UUID, page int, limit int)) *MockRoomService_ListMy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockRoomService_ListMy_Call) Return(_a0 []models.Room, _a1 int64, _a2 error) *MockRoomService_ListMy_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRoomService_ListMy_Call) RunAndReturn(run func(uuid.UUID, int, int) ([]models.Room, int64, error)) *MockRoomService_ListMy_Call {
	_c.Call.Return(run)
	return _c
}

// ListPublic provides a mock function with given fields: page, limit, search, categoryId
func (_m *MockRoomService) ListPublic(page int, limit int, search string, categoryId *uuid.UUID) ([]models.Room, int64, error) {
	ret := _m.Called(page, limit, search, categoryId)

	if len(ret) == 0 {
		panic("no return value specified for ListPublic")
	}

	var r0 []models.Room
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, string, *uuid.UUID) ([]models.Room, int64, error)); ok {
		return rf(page, limit, search, categoryId)
	}
	if rf, ok := ret.Get(0).(func(int, int, string, *uuid.UUID) []models.Room); ok {
		r0 = rf(page, limit, search, categoryId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string, *uuid.UUID) int64); ok {
		r1 = rf(page, limit, search, categoryId)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int, string, *uuid.UUID) error); ok {
		r2 = rf(page, limit, search, categoryId)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRoomService_ListPublic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPublic'
type MockRoomService_ListPublic_Call struct {
	*mock.Call
}

// ListPublic is a helper method to define mock.On call
//   - page int
//   - limit int
//   - search string
//   - categoryId *uuid.UUID
func (_e *MockRoomService_Expecter) ListPublic(page interface{}, limit interface{}, search interface{}, categoryId interface{}) *MockRoomService_ListPublic_Call {
	return &MockRoomService_ListPublic_Call{Call: _e.mock.On("ListPublic", page, limit, search, categoryId)}
}

func (_c *MockRoomService_ListPublic_Call) Run(run func(page int, limit int, search string, categoryId *uuid.UUID)) *MockRoomService_ListPublic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int), args[2].(string), args[3].(*uuid.UUID))
	})
	return _c
}

func (_c *MockRoomService_ListPublic_Call) Return(_a0 []models.Room, _a1 int64, _a2 error) *MockRoomService_ListPublic_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRoomService_ListPublic_Call) RunAndReturn(run func(int, int, string, *uuid.UUID) ([]models.Room, int64, error)) *MockRoomService_ListPublic_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, room, thumbnailData, thumbnailFilename, userId
func (_m *MockRoomService) Update(ctx context.Context, room *models.Room, thumbnailData []byte, thumbnailFilename string, userId uuid.UUID) (uuid.UUID, error) {
	ret := _m.Called(ctx, room, thumbnailData, thumbnailFilename, userId)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Room, []byte, string, uuid.UUID) (uuid.UUID, error)); ok {
		return rf(ctx, room, thumbnailData, thumbnailFilename, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Room, []byte, string, uuid.UUID) uuid.UUID); ok {
		r0 = rf(ctx, room, thumbnailData, thumbnailFilename, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Room, []byte, string, uuid.UUID) error); ok {
		r1 = rf(ctx, room, thumbnailData, thumbnailFilename, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRoomService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - room *models.Room
//   - thumbnailData []byte
//   - thumbnailFilename string
//   - userId uuid.UUID
func (_e *MockRoomService_Expecter) Update(ctx interface{}, room interface{}, thumbnailData interface{}, thumbnailFilename interface{}, userId interface{}) *MockRoomService_Update_Call {
	return &MockRoomService_Update_Call{Call: _e.mock.On("Update", ctx, room, thumbnailData, thumbnailFilename, userId)}
}

func (_c *MockRoomService_Update_Call) Run(run func(ctx context.Context, room *models.Room, thumbnailData []byte, thumbnailFilename string, userId uuid.UUID)) *MockRoomService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Room), args[2].([]byte), args[3].(string), args[4].(uuid.UUID))
	})
	return _c
}

func (_c *MockRoomService_Update_Call) Return(_a0 uuid.UUID, _a1 error) *MockRoomService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomService_Update_Call) RunAndReturn(run func(context.Context, *models.Room, []byte, string, uuid.UUID) (uuid.UUID, error)) *MockRoomService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoomService creates a new instance of MockRoomService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomService {
	mock := &MockRoomService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
