syntax = "proto3";

package room;

option go_package = "webby/admin-service/internal/grpc/userpb";

import "google/protobuf/empty.proto";

service UserGrpcService {
  rpc BanUser(BanUserRequest) returns (google.protobuf.Empty);
  rpc GetMonthlyRegistrations(google.protobuf.Empty) returns (GetMonthlyRegistrationsResponse);
  rpc GetMonthlySubscriptions(google.protobuf.Empty) returns (GetMonthlySubscriptionsResponse);
  rpc GetTotalRegistrations(google.protobuf.Empty) returns (GetTotalRegistrationsResponse);
	rpc GetMonthRevenue(google.protobuf.Empty) returns (GetMonthRevenueResponse);
}

message BanUserRequest {
  string userID = 1;
}

message GetMonthlyRegistrationsResponse {
  map<int32, int32> registrations = 1;
}

message GetMonthlySubscriptionsResponse {
  map<int32, int32> subscriptions  = 1;
}

message GetTotalRegistrationsResponse {
  int32 totalRegistrations  = 1;
}

message GetMonthRevenueResponse {
  int32 monthRevenue  = 1;
}