// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: vote/vote.proto

package votepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VoteGrpcService_GetActiveVotes_FullMethodName = "/vote.VoteGrpcService/GetActiveVotes"
)

// VoteGrpcServiceClient is the client API for VoteGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoteGrpcServiceClient interface {
	GetActiveVotes(ctx context.Context, in *GetActiveVotesRequest, opts ...grpc.CallOption) (*GetActiveVotesResponse, error)
}

type voteGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVoteGrpcServiceClient(cc grpc.ClientConnInterface) VoteGrpcServiceClient {
	return &voteGrpcServiceClient{cc}
}

func (c *voteGrpcServiceClient) GetActiveVotes(ctx context.Context, in *GetActiveVotesRequest, opts ...grpc.CallOption) (*GetActiveVotesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveVotesResponse)
	err := c.cc.Invoke(ctx, VoteGrpcService_GetActiveVotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoteGrpcServiceServer is the server API for VoteGrpcService service.
// All implementations must embed UnimplementedVoteGrpcServiceServer
// for forward compatibility.
type VoteGrpcServiceServer interface {
	GetActiveVotes(context.Context, *GetActiveVotesRequest) (*GetActiveVotesResponse, error)
	mustEmbedUnimplementedVoteGrpcServiceServer()
}

// UnimplementedVoteGrpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVoteGrpcServiceServer struct{}

func (UnimplementedVoteGrpcServiceServer) GetActiveVotes(context.Context, *GetActiveVotesRequest) (*GetActiveVotesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveVotes not implemented")
}
func (UnimplementedVoteGrpcServiceServer) mustEmbedUnimplementedVoteGrpcServiceServer() {}
func (UnimplementedVoteGrpcServiceServer) testEmbeddedByValue()                         {}

// UnsafeVoteGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoteGrpcServiceServer will
// result in compilation errors.
type UnsafeVoteGrpcServiceServer interface {
	mustEmbedUnimplementedVoteGrpcServiceServer()
}

func RegisterVoteGrpcServiceServer(s grpc.ServiceRegistrar, srv VoteGrpcServiceServer) {
	// If the following call panics, it indicates UnimplementedVoteGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VoteGrpcService_ServiceDesc, srv)
}

func _VoteGrpcService_GetActiveVotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveVotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoteGrpcServiceServer).GetActiveVotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoteGrpcService_GetActiveVotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoteGrpcServiceServer).GetActiveVotes(ctx, req.(*GetActiveVotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VoteGrpcService_ServiceDesc is the grpc.ServiceDesc for VoteGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoteGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vote.VoteGrpcService",
	HandlerType: (*VoteGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetActiveVotes",
			Handler:    _VoteGrpcService_GetActiveVotes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vote/vote.proto",
}
