// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: proto/user/user.proto

package userpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserGrpcService_BanUser_FullMethodName                 = "/UserGrpcService/BanUser"
	UserGrpcService_GetMonthlyRegistrations_FullMethodName = "/UserGrpcService/GetMonthlyRegistrations"
	UserGrpcService_GetMonthlySubscriptions_FullMethodName = "/UserGrpcService/GetMonthlySubscriptions"
	UserGrpcService_GetTotalRegistrations_FullMethodName   = "/UserGrpcService/GetTotalRegistrations"
	UserGrpcService_GetMonthRevenue_FullMethodName         = "/UserGrpcService/GetMonthRevenue"
)

// UserGrpcServiceClient is the client API for UserGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserGrpcServiceClient interface {
	BanUser(ctx context.Context, in *BanUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetMonthlyRegistrations(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMonthlyRegistrationsResponse, error)
	GetMonthlySubscriptions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMonthlySubscriptionsResponse, error)
	GetTotalRegistrations(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetTotalRegistrationsResponse, error)
	GetMonthRevenue(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMonthRevenueResponse, error)
}

type userGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserGrpcServiceClient(cc grpc.ClientConnInterface) UserGrpcServiceClient {
	return &userGrpcServiceClient{cc}
}

func (c *userGrpcServiceClient) BanUser(ctx context.Context, in *BanUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserGrpcService_BanUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGrpcServiceClient) GetMonthlyRegistrations(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMonthlyRegistrationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMonthlyRegistrationsResponse)
	err := c.cc.Invoke(ctx, UserGrpcService_GetMonthlyRegistrations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGrpcServiceClient) GetMonthlySubscriptions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMonthlySubscriptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMonthlySubscriptionsResponse)
	err := c.cc.Invoke(ctx, UserGrpcService_GetMonthlySubscriptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGrpcServiceClient) GetTotalRegistrations(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetTotalRegistrationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTotalRegistrationsResponse)
	err := c.cc.Invoke(ctx, UserGrpcService_GetTotalRegistrations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGrpcServiceClient) GetMonthRevenue(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMonthRevenueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMonthRevenueResponse)
	err := c.cc.Invoke(ctx, UserGrpcService_GetMonthRevenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserGrpcServiceServer is the server API for UserGrpcService service.
// All implementations must embed UnimplementedUserGrpcServiceServer
// for forward compatibility.
type UserGrpcServiceServer interface {
	BanUser(context.Context, *BanUserRequest) (*emptypb.Empty, error)
	GetMonthlyRegistrations(context.Context, *emptypb.Empty) (*GetMonthlyRegistrationsResponse, error)
	GetMonthlySubscriptions(context.Context, *emptypb.Empty) (*GetMonthlySubscriptionsResponse, error)
	GetTotalRegistrations(context.Context, *emptypb.Empty) (*GetTotalRegistrationsResponse, error)
	GetMonthRevenue(context.Context, *emptypb.Empty) (*GetMonthRevenueResponse, error)
	mustEmbedUnimplementedUserGrpcServiceServer()
}

// UnimplementedUserGrpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserGrpcServiceServer struct{}

func (UnimplementedUserGrpcServiceServer) BanUser(context.Context, *BanUserRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method BanUser not implemented")
}
func (UnimplementedUserGrpcServiceServer) GetMonthlyRegistrations(context.Context, *emptypb.Empty) (*GetMonthlyRegistrationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMonthlyRegistrations not implemented")
}
func (UnimplementedUserGrpcServiceServer) GetMonthlySubscriptions(context.Context, *emptypb.Empty) (*GetMonthlySubscriptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMonthlySubscriptions not implemented")
}
func (UnimplementedUserGrpcServiceServer) GetTotalRegistrations(context.Context, *emptypb.Empty) (*GetTotalRegistrationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTotalRegistrations not implemented")
}
func (UnimplementedUserGrpcServiceServer) GetMonthRevenue(context.Context, *emptypb.Empty) (*GetMonthRevenueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMonthRevenue not implemented")
}
func (UnimplementedUserGrpcServiceServer) mustEmbedUnimplementedUserGrpcServiceServer() {}
func (UnimplementedUserGrpcServiceServer) testEmbeddedByValue()                         {}

// UnsafeUserGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserGrpcServiceServer will
// result in compilation errors.
type UnsafeUserGrpcServiceServer interface {
	mustEmbedUnimplementedUserGrpcServiceServer()
}

func RegisterUserGrpcServiceServer(s grpc.ServiceRegistrar, srv UserGrpcServiceServer) {
	// If the following call panics, it indicates UnimplementedUserGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserGrpcService_ServiceDesc, srv)
}

func _UserGrpcService_BanUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BanUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGrpcServiceServer).BanUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserGrpcService_BanUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGrpcServiceServer).BanUser(ctx, req.(*BanUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGrpcService_GetMonthlyRegistrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGrpcServiceServer).GetMonthlyRegistrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserGrpcService_GetMonthlyRegistrations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGrpcServiceServer).GetMonthlyRegistrations(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGrpcService_GetMonthlySubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGrpcServiceServer).GetMonthlySubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserGrpcService_GetMonthlySubscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGrpcServiceServer).GetMonthlySubscriptions(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGrpcService_GetTotalRegistrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGrpcServiceServer).GetTotalRegistrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserGrpcService_GetTotalRegistrations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGrpcServiceServer).GetTotalRegistrations(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGrpcService_GetMonthRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGrpcServiceServer).GetMonthRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserGrpcService_GetMonthRevenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGrpcServiceServer).GetMonthRevenue(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// UserGrpcService_ServiceDesc is the grpc.ServiceDesc for UserGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UserGrpcService",
	HandlerType: (*UserGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BanUser",
			Handler:    _UserGrpcService_BanUser_Handler,
		},
		{
			MethodName: "GetMonthlyRegistrations",
			Handler:    _UserGrpcService_GetMonthlyRegistrations_Handler,
		},
		{
			MethodName: "GetMonthlySubscriptions",
			Handler:    _UserGrpcService_GetMonthlySubscriptions_Handler,
		},
		{
			MethodName: "GetTotalRegistrations",
			Handler:    _UserGrpcService_GetTotalRegistrations_Handler,
		},
		{
			MethodName: "GetMonthRevenue",
			Handler:    _UserGrpcService_GetMonthRevenue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user/user.proto",
}
