apiVersion: v1
kind: Service
metadata:
  name: achievement-service
spec:
  selector:
    app: achievement-service
  type: ClusterIP
  ports:
    - name: rest
      port: 5008
      targetPort: 5008
    - name: grpc
      port: 5009
      targetPort: 5009
