// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "webby/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockMyLister is an autogenerated mock type for the MyLister type
type MockMyLister struct {
	mock.Mock
}

type MockMyLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMyLister) EXPECT() *MockMyLister_Expecter {
	return &MockMyLister_Expecter{mock: &_m.Mock}
}

// ListMy provides a mock function with given fields: id, page, limit
func (_m *MockMyLister) ListMy(id uuid.UUID, page int, limit int) ([]models.Room, int64, error) {
	ret := _m.Called(id, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListMy")
	}

	var r0 []models.Room
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int) ([]models.Room, int64, error)); ok {
		return rf(id, page, limit)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int) []models.Room); ok {
		r0 = rf(id, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, int, int) int64); ok {
		r1 = rf(id, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID, int, int) error); ok {
		r2 = rf(id, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockMyLister_ListMy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMy'
type MockMyLister_ListMy_Call struct {
	*mock.Call
}

// ListMy is a helper method to define mock.On call
//   - id uuid.UUID
//   - page int
//   - limit int
func (_e *MockMyLister_Expecter) ListMy(id interface{}, page interface{}, limit interface{}) *MockMyLister_ListMy_Call {
	return &MockMyLister_ListMy_Call{Call: _e.mock.On("ListMy", id, page, limit)}
}

func (_c *MockMyLister_ListMy_Call) Run(run func(id uuid.UUID, page int, limit int)) *MockMyLister_ListMy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockMyLister_ListMy_Call) Return(_a0 []models.Room, _a1 int64, _a2 error) *MockMyLister_ListMy_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockMyLister_ListMy_Call) RunAndReturn(run func(uuid.UUID, int, int) ([]models.Room, int64, error)) *MockMyLister_ListMy_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMyLister creates a new instance of MockMyLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMyLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMyLister {
	mock := &MockMyLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
