// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: proto/complaint/complaint.proto

package complaintpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetComplaintByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComplaintID   string                 `protobuf:"bytes,1,opt,name=complaintID,proto3" json:"complaintID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetComplaintByIDRequest) Reset() {
	*x = GetComplaintByIDRequest{}
	mi := &file_proto_complaint_complaint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetComplaintByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetComplaintByIDRequest) ProtoMessage() {}

func (x *GetComplaintByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_complaint_complaint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetComplaintByIDRequest.ProtoReflect.Descriptor instead.
func (*GetComplaintByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_complaint_complaint_proto_rawDescGZIP(), []int{0}
}

func (x *GetComplaintByIDRequest) GetComplaintID() string {
	if x != nil {
		return x.ComplaintID
	}
	return ""
}

type GetComplaintByIDResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ComplaintID    string                 `protobuf:"bytes,1,opt,name=complaintID,proto3" json:"complaintID,omitempty"`
	AuthorId       string                 `protobuf:"bytes,2,opt,name=authorId,proto3" json:"authorId,omitempty"`
	TargetType     string                 `protobuf:"bytes,3,opt,name=targetType,proto3" json:"targetType,omitempty"`
	TargetId       string                 `protobuf:"bytes,4,opt,name=targetId,proto3" json:"targetId,omitempty"`
	ReasonType     string                 `protobuf:"bytes,5,opt,name=reasonType,proto3" json:"reasonType,omitempty"`
	AdditionalInfo string                 `protobuf:"bytes,6,opt,name=additionalInfo,proto3" json:"additionalInfo,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetComplaintByIDResponse) Reset() {
	*x = GetComplaintByIDResponse{}
	mi := &file_proto_complaint_complaint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetComplaintByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetComplaintByIDResponse) ProtoMessage() {}

func (x *GetComplaintByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_complaint_complaint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetComplaintByIDResponse.ProtoReflect.Descriptor instead.
func (*GetComplaintByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_complaint_complaint_proto_rawDescGZIP(), []int{1}
}

func (x *GetComplaintByIDResponse) GetComplaintID() string {
	if x != nil {
		return x.ComplaintID
	}
	return ""
}

func (x *GetComplaintByIDResponse) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *GetComplaintByIDResponse) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *GetComplaintByIDResponse) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *GetComplaintByIDResponse) GetReasonType() string {
	if x != nil {
		return x.ReasonType
	}
	return ""
}

func (x *GetComplaintByIDResponse) GetAdditionalInfo() string {
	if x != nil {
		return x.AdditionalInfo
	}
	return ""
}

func (x *GetComplaintByIDResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_proto_complaint_complaint_proto protoreflect.FileDescriptor

const file_proto_complaint_complaint_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/complaint/complaint.proto\x1a\x1fgoogle/protobuf/timestamp.proto\";\n" +
	"\x17GetComplaintByIDRequest\x12 \n" +
	"\vcomplaintID\x18\x01 \x01(\tR\vcomplaintID\"\x96\x02\n" +
	"\x18GetComplaintByIDResponse\x12 \n" +
	"\vcomplaintID\x18\x01 \x01(\tR\vcomplaintID\x12\x1a\n" +
	"\bauthorId\x18\x02 \x01(\tR\bauthorId\x12\x1e\n" +
	"\n" +
	"targetType\x18\x03 \x01(\tR\n" +
	"targetType\x12\x1a\n" +
	"\btargetId\x18\x04 \x01(\tR\btargetId\x12\x1e\n" +
	"\n" +
	"reasonType\x18\x05 \x01(\tR\n" +
	"reasonType\x12&\n" +
	"\x0eadditionalInfo\x18\x06 \x01(\tR\x0eadditionalInfo\x128\n" +
	"\tcreatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2_\n" +
	"\x14ComplaintGrpcService\x12G\n" +
	"\x10GetComplaintByID\x12\x18.GetComplaintByIDRequest\x1a\x19.GetComplaintByIDResponseB/Z-webby/admin-service/internal/grpc/complaintpbb\x06proto3"

var (
	file_proto_complaint_complaint_proto_rawDescOnce sync.Once
	file_proto_complaint_complaint_proto_rawDescData []byte
)

func file_proto_complaint_complaint_proto_rawDescGZIP() []byte {
	file_proto_complaint_complaint_proto_rawDescOnce.Do(func() {
		file_proto_complaint_complaint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_complaint_complaint_proto_rawDesc), len(file_proto_complaint_complaint_proto_rawDesc)))
	})
	return file_proto_complaint_complaint_proto_rawDescData
}

var file_proto_complaint_complaint_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_complaint_complaint_proto_goTypes = []any{
	(*GetComplaintByIDRequest)(nil),  // 0: GetComplaintByIDRequest
	(*GetComplaintByIDResponse)(nil), // 1: GetComplaintByIDResponse
	(*timestamppb.Timestamp)(nil),    // 2: google.protobuf.Timestamp
}
var file_proto_complaint_complaint_proto_depIdxs = []int32{
	2, // 0: GetComplaintByIDResponse.createdAt:type_name -> google.protobuf.Timestamp
	0, // 1: ComplaintGrpcService.GetComplaintByID:input_type -> GetComplaintByIDRequest
	1, // 2: ComplaintGrpcService.GetComplaintByID:output_type -> GetComplaintByIDResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_complaint_complaint_proto_init() }
func file_proto_complaint_complaint_proto_init() {
	if File_proto_complaint_complaint_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_complaint_complaint_proto_rawDesc), len(file_proto_complaint_complaint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_complaint_complaint_proto_goTypes,
		DependencyIndexes: file_proto_complaint_complaint_proto_depIdxs,
		MessageInfos:      file_proto_complaint_complaint_proto_msgTypes,
	}.Build()
	File_proto_complaint_complaint_proto = out.File
	file_proto_complaint_complaint_proto_goTypes = nil
	file_proto_complaint_complaint_proto_depIdxs = nil
}
