// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"context"
	"webby/internal/services"

	"github.com/google/uuid"
	"github.com/stretchr/testify/mock"
)

type MockCreator struct {
	mock.Mock
}

type MockCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreator) EXPECT() *MockCreator_Expecter {
	return &MockCreator_Expecter{mock: &_m.Mock}
}

func (_m *MockCreator) CreateVote(ctx context.Context, roomId, userId uuid.UUID, voteType, voteText string, durationSeconds int, choices []services.CreateChoiceInput) (*services.VoteDetail, error) {
	ret := _m.Called(ctx, roomId, userId, voteType, voteText, durationSeconds, choices)

	if len(ret) == 0 {
		panic("no return value specified for CreateVote")
	}

	var r0 *services.VoteDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, int, []services.CreateChoiceInput) (*services.VoteDetail, error)); ok {
		return rf(ctx, roomId, userId, voteType, voteText, durationSeconds, choices)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, int, []services.CreateChoiceInput) *services.VoteDetail); ok {
		r0 = rf(ctx, roomId, userId, voteType, voteText, durationSeconds, choices)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.VoteDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, string, int, []services.CreateChoiceInput) error); ok {
		r1 = rf(ctx, roomId, userId, voteType, voteText, durationSeconds, choices)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockCreator_CreateVote_Call struct {
	*mock.Call
}

func (_e *MockCreator_Expecter) CreateVote(ctx interface{}, roomId interface{}, userId interface{}, voteType interface{}, voteText interface{}, durationSeconds interface{}, choices interface{}) *MockCreator_CreateVote_Call {
	return &MockCreator_CreateVote_Call{Call: _e.mock.On("CreateVote", ctx, roomId, userId, voteType, voteText, durationSeconds, choices)}
}

func (_c *MockCreator_CreateVote_Call) Run(run func(ctx context.Context, roomId, userId uuid.UUID, voteType, voteText string, durationSeconds int, choices []services.CreateChoiceInput)) *MockCreator_CreateVote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].(string), args[5].(int), args[6].([]services.CreateChoiceInput))
	})
	return _c
}

func (_c *MockCreator_CreateVote_Call) Return(_a0 *services.VoteDetail, _a1 error) *MockCreator_CreateVote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func NewMockCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreator {
	mock := &MockCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
