apiVersion: v1
kind: Service
metadata:
  name: video-service
spec:
  selector:
    app: video-service
  type: ClusterIP
  ports:
    - name: rest
      port: 5003
      targetPort: 5003
    - name: grpc
      port: 5005
      targetPort: 5005
