resources:
  - api-gateway/
  - auth-service/
  - notification-service/
  - user-service/
  - video-service/
  - achievement-service/
  - admin-service/
  - chat-service/
  - room-service/
  - room-category-service/
  - room-queue-service/
  - votes-service/
  - ws-gateway/
  - redis/
  - infisical/
  - ingress/ 
  - web/