// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	services "webby/internal/services"

	uuid "github.com/google/uuid"
)

// MockQueueLister is an autogenerated mock type for the QueueLister type
type MockQueueLister struct {
	mock.Mock
}

type MockQueueLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueueLister) EXPECT() *MockQueueLister_Expecter {
	return &MockQueueLister_Expecter{mock: &_m.Mock}
}

// GetQueue provides a mock function with given fields: ctx, roomId, userId
func (_m *MockQueueLister) GetQueue(ctx context.Context, roomId uuid.UUID, userId uuid.UUID) ([]services.QueueItemEnriched, error) {
	ret := _m.Called(ctx, roomId, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetQueue")
	}

	var r0 []services.QueueItemEnriched
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]services.QueueItemEnriched, error)); ok {
		return rf(ctx, roomId, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []services.QueueItemEnriched); ok {
		r0 = rf(ctx, roomId, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]services.QueueItemEnriched)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, roomId, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQueueLister_GetQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueue'
type MockQueueLister_GetQueue_Call struct {
	*mock.Call
}

// GetQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - roomId uuid.UUID
//   - userId uuid.UUID
func (_e *MockQueueLister_Expecter) GetQueue(ctx interface{}, roomId interface{}, userId interface{}) *MockQueueLister_GetQueue_Call {
	return &MockQueueLister_GetQueue_Call{Call: _e.mock.On("GetQueue", ctx, roomId, userId)}
}

func (_c *MockQueueLister_GetQueue_Call) Run(run func(ctx context.Context, roomId uuid.UUID, userId uuid.UUID)) *MockQueueLister_GetQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockQueueLister_GetQueue_Call) Return(_a0 []services.QueueItemEnriched, _a1 error) *MockQueueLister_GetQueue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQueueLister_GetQueue_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]services.QueueItemEnriched, error)) *MockQueueLister_GetQueue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueueLister creates a new instance of MockQueueLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueueLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueueLister {
	mock := &MockQueueLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
