// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: proto/queue/queue.proto

package queuepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QueueGrpcService_MoveToTop_FullMethodName = "/queue.QueueGrpcService/MoveToTop"
)

// QueueGrpcServiceClient is the client API for QueueGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueueGrpcServiceClient interface {
	MoveToTop(ctx context.Context, in *MoveToTopRequest, opts ...grpc.CallOption) (*MoveToTopResponse, error)
}

type queueGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQueueGrpcServiceClient(cc grpc.ClientConnInterface) QueueGrpcServiceClient {
	return &queueGrpcServiceClient{cc}
}

func (c *queueGrpcServiceClient) MoveToTop(ctx context.Context, in *MoveToTopRequest, opts ...grpc.CallOption) (*MoveToTopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveToTopResponse)
	err := c.cc.Invoke(ctx, QueueGrpcService_MoveToTop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueueGrpcServiceServer is the server API for QueueGrpcService service.
// All implementations must embed UnimplementedQueueGrpcServiceServer
// for forward compatibility.
type QueueGrpcServiceServer interface {
	MoveToTop(context.Context, *MoveToTopRequest) (*MoveToTopResponse, error)
	mustEmbedUnimplementedQueueGrpcServiceServer()
}

// UnimplementedQueueGrpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueueGrpcServiceServer struct{}

func (UnimplementedQueueGrpcServiceServer) MoveToTop(context.Context, *MoveToTopRequest) (*MoveToTopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveToTop not implemented")
}
func (UnimplementedQueueGrpcServiceServer) mustEmbedUnimplementedQueueGrpcServiceServer() {}
func (UnimplementedQueueGrpcServiceServer) testEmbeddedByValue()                          {}

// UnsafeQueueGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueueGrpcServiceServer will
// result in compilation errors.
type UnsafeQueueGrpcServiceServer interface {
	mustEmbedUnimplementedQueueGrpcServiceServer()
}

func RegisterQueueGrpcServiceServer(s grpc.ServiceRegistrar, srv QueueGrpcServiceServer) {
	// If the following call panics, it indicates UnimplementedQueueGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QueueGrpcService_ServiceDesc, srv)
}

func _QueueGrpcService_MoveToTop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveToTopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueGrpcServiceServer).MoveToTop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueGrpcService_MoveToTop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueGrpcServiceServer).MoveToTop(ctx, req.(*MoveToTopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QueueGrpcService_ServiceDesc is the grpc.ServiceDesc for QueueGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueueGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "queue.QueueGrpcService",
	HandlerType: (*QueueGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MoveToTop",
			Handler:    _QueueGrpcService_MoveToTop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/queue/queue.proto",
}
