// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: proto/queue/queue.proto

package queuepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MakeNextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomID        string                 `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	QueueItemID   string                 `protobuf:"bytes,2,opt,name=queueItemID,proto3" json:"queueItemID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeNextRequest) Reset() {
	*x = MakeNextRequest{}
	mi := &file_proto_queue_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeNextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeNextRequest) ProtoMessage() {}

func (x *MakeNextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeNextRequest.ProtoReflect.Descriptor instead.
func (*MakeNextRequest) Descriptor() ([]byte, []int) {
	return file_proto_queue_queue_proto_rawDescGZIP(), []int{0}
}

func (x *MakeNextRequest) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

func (x *MakeNextRequest) GetQueueItemID() string {
	if x != nil {
		return x.QueueItemID
	}
	return ""
}

var File_proto_queue_queue_proto protoreflect.FileDescriptor

const file_proto_queue_queue_proto_rawDesc = "" +
	"\n" +
	"\x17proto/queue/queue.proto\x12\x05queue\x1a\x1bgoogle/protobuf/empty.proto\"K\n" +
	"\x0fMakeNextRequest\x12\x16\n" +
	"\x06roomID\x18\x01 \x01(\tR\x06roomID\x12 \n" +
	"\vqueueItemID\x18\x02 \x01(\tR\vqueueItemID2N\n" +
	"\x10QueueGrpcService\x12:\n" +
	"\bMakeNext\x12\x16.queue.MakeNextRequest\x1a\x16.google.protobuf.EmptyB*Z(webby/vote-service/internal/grpc/queuepbb\x06proto3"

var (
	file_proto_queue_queue_proto_rawDescOnce sync.Once
	file_proto_queue_queue_proto_rawDescData []byte
)

func file_proto_queue_queue_proto_rawDescGZIP() []byte {
	file_proto_queue_queue_proto_rawDescOnce.Do(func() {
		file_proto_queue_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_queue_queue_proto_rawDesc), len(file_proto_queue_queue_proto_rawDesc)))
	})
	return file_proto_queue_queue_proto_rawDescData
}

var file_proto_queue_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_queue_queue_proto_goTypes = []any{
	(*MakeNextRequest)(nil), // 0: queue.MakeNextRequest
	(*emptypb.Empty)(nil),   // 1: google.protobuf.Empty
}
var file_proto_queue_queue_proto_depIdxs = []int32{
	0, // 0: queue.QueueGrpcService.MakeNext:input_type -> queue.MakeNextRequest
	1, // 1: queue.QueueGrpcService.MakeNext:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_queue_queue_proto_init() }
func file_proto_queue_queue_proto_init() {
	if File_proto_queue_queue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_queue_queue_proto_rawDesc), len(file_proto_queue_queue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_queue_queue_proto_goTypes,
		DependencyIndexes: file_proto_queue_queue_proto_depIdxs,
		MessageInfos:      file_proto_queue_queue_proto_msgTypes,
	}.Build()
	File_proto_queue_queue_proto = out.File
	file_proto_queue_queue_proto_goTypes = nil
	file_proto_queue_queue_proto_depIdxs = nil
}
