apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: admin-service
          image: eu-frankfurt-1.ocir.io/fr3wma7oqvij/webby-admin-service:latest
          ports:
            - containerPort: 8085
          env:
            - name: ENV
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: EnvЕ
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: UriConnectionString
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: JwtAccessSecretKey
            - name: HTTP_ADMIN_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: HttpAdminAddress
            - name: GRPC_MEDIA_SERVICE_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: GoVideoGrpcServiceUrl
            - name: GRPC_ROOM_SERVICE_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: RoomGrpcServiceUrl
            - name: GRPC_COMPLAINT_SERVICE_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: GoUserGrpcServiceUrl
            - name: GRPC_NOTIFICATION_SERVICE_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: GoNotificationGrpcServiceUrl
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /livez
              port: 8085
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8085
            initialDelaySeconds: 10
            periodSeconds: 10
