// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"context"
	"webby/internal/services"

	"github.com/google/uuid"
	"github.com/stretchr/testify/mock"
)

type MockCaster struct {
	mock.Mock
}

type MockCaster_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCaster) EXPECT() *MockCaster_Expecter {
	return &MockCaster_Expecter{mock: &_m.Mock}
}

func (_m *MockCaster) CastVote(ctx context.Context, voteId, choiceId, userId uuid.UUID) (*services.VoteDetail, error) {
	ret := _m.Called(ctx, voteId, choiceId, userId)

	if len(ret) == 0 {
		panic("no return value specified for CastVote")
	}

	var r0 *services.VoteDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (*services.VoteDetail, error)); ok {
		return rf(ctx, voteId, choiceId, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) *services.VoteDetail); ok {
		r0 = rf(ctx, voteId, choiceId, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.VoteDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, voteId, choiceId, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockCaster_CastVote_Call struct {
	*mock.Call
}

func (_e *MockCaster_Expecter) CastVote(ctx interface{}, voteId interface{}, choiceId interface{}, userId interface{}) *MockCaster_CastVote_Call {
	return &MockCaster_CastVote_Call{Call: _e.mock.On("CastVote", ctx, voteId, choiceId, userId)}
}

func (_c *MockCaster_CastVote_Call) Run(run func(ctx context.Context, voteId, choiceId, userId uuid.UUID)) *MockCaster_CastVote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockCaster_CastVote_Call) Return(_a0 *services.VoteDetail, _a1 error) *MockCaster_CastVote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func NewMockCaster(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCaster {
	mock := &MockCaster{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
