apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-queue-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-queue-service
  template:
    metadata:
      labels:
        app: room-queue-service
    spec:
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: room-queue-service
          image: eu-frankfurt-1.ocir.io/fr3wma7oqvij/webby-room-queue-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: ENV
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: Env
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: UriConnectionString
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: JwtAccessSecretKey
            - name: REDIS_ADDR
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: RedisAddress
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: RedisPassword
            - name: HTTP_ROOM_QUEUE_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: HttpRoomQueueAddress
            - name: GRPC_ROOM_QUEUE_SERVICE_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: RoomQueueGrpcServiceUrl
            - name: GRPC_MEDIA_SERVICE_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: GoVideoGrpcServiceUrl
            - name: GRPC_CHAT_SERVICE_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: ChatGrpcServiceUrl
            - name: GRPC_ROOM_SERVICE_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: webby-secrets
                  key: RoomGrpcServiceUrl
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /livez
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 10
