// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: proto/chat/chat.proto

package chatpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatGrpcService_GetChatIDByRoomID_FullMethodName = "/chat.ChatGrpcService/GetChatIDByRoomID"
)

// ChatGrpcServiceClient is the client API for ChatGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatGrpcServiceClient interface {
	GetChatIDByRoomID(ctx context.Context, in *GetChatIDByRoomIDRequest, opts ...grpc.CallOption) (*ChatIDByRoomIDResponse, error)
}

type chatGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatGrpcServiceClient(cc grpc.ClientConnInterface) ChatGrpcServiceClient {
	return &chatGrpcServiceClient{cc}
}

func (c *chatGrpcServiceClient) GetChatIDByRoomID(ctx context.Context, in *GetChatIDByRoomIDRequest, opts ...grpc.CallOption) (*ChatIDByRoomIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatIDByRoomIDResponse)
	err := c.cc.Invoke(ctx, ChatGrpcService_GetChatIDByRoomID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatGrpcServiceServer is the server API for ChatGrpcService service.
// All implementations must embed UnimplementedChatGrpcServiceServer
// for forward compatibility.
type ChatGrpcServiceServer interface {
	GetChatIDByRoomID(context.Context, *GetChatIDByRoomIDRequest) (*ChatIDByRoomIDResponse, error)
	mustEmbedUnimplementedChatGrpcServiceServer()
}

// UnimplementedChatGrpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatGrpcServiceServer struct{}

func (UnimplementedChatGrpcServiceServer) GetChatIDByRoomID(context.Context, *GetChatIDByRoomIDRequest) (*ChatIDByRoomIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChatIDByRoomID not implemented")
}
func (UnimplementedChatGrpcServiceServer) mustEmbedUnimplementedChatGrpcServiceServer() {}
func (UnimplementedChatGrpcServiceServer) testEmbeddedByValue()                         {}

// UnsafeChatGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatGrpcServiceServer will
// result in compilation errors.
type UnsafeChatGrpcServiceServer interface {
	mustEmbedUnimplementedChatGrpcServiceServer()
}

func RegisterChatGrpcServiceServer(s grpc.ServiceRegistrar, srv ChatGrpcServiceServer) {
	// If the following call panics, it indicates UnimplementedChatGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatGrpcService_ServiceDesc, srv)
}

func _ChatGrpcService_GetChatIDByRoomID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatIDByRoomIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatGrpcServiceServer).GetChatIDByRoomID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatGrpcService_GetChatIDByRoomID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatGrpcServiceServer).GetChatIDByRoomID(ctx, req.(*GetChatIDByRoomIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatGrpcService_ServiceDesc is the grpc.ServiceDesc for ChatGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatGrpcService",
	HandlerType: (*ChatGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChatIDByRoomID",
			Handler:    _ChatGrpcService_GetChatIDByRoomID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/chat/chat.proto",
}
