// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCreator is an autogenerated mock type for the Creator type
type MockCreator struct {
	mock.Mock
}

type MockCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreator) EXPECT() *MockCreator_Expecter {
	return &MockCreator_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, name
func (_m *MockCreator) Create(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCreator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCreator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockCreator_Expecter) Create(ctx interface{}, name interface{}) *MockCreator_Create_Call {
	return &MockCreator_Create_Call{Call: _e.mock.On("Create", ctx, name)}
}

func (_c *MockCreator_Create_Call) Run(run func(ctx context.Context, name string)) *MockCreator_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCreator_Create_Call) Return(_a0 error) *MockCreator_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCreator_Create_Call) RunAndReturn(run func(context.Context, string) error) *MockCreator_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreator creates a new instance of MockCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreator {
	mock := &MockCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
