// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockMemberAdder is an autogenerated mock type for the MemberAdder type
type MockMemberAdder struct {
	mock.Mock
}

type MockMemberAdder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMemberAdder) EXPECT() *MockMemberAdder_Expecter {
	return &MockMemberAdder_Expecter{mock: &_m.Mock}
}

// AddMembers provides a mock function with given fields: ctx, roomId, memberIds, userId
func (_m *MockMemberAdder) AddMembers(ctx context.Context, roomId uuid.UUID, memberIds []uuid.UUID, userId uuid.UUID) error {
	ret := _m.Called(ctx, roomId, memberIds, userId)

	if len(ret) == 0 {
		panic("no return value specified for AddMembers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, roomId, memberIds, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMemberAdder_AddMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMembers'
type MockMemberAdder_AddMembers_Call struct {
	*mock.Call
}

// AddMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - roomId uuid.UUID
//   - memberIds []uuid.UUID
//   - userId uuid.UUID
func (_e *MockMemberAdder_Expecter) AddMembers(ctx interface{}, roomId interface{}, memberIds interface{}, userId interface{}) *MockMemberAdder_AddMembers_Call {
	return &MockMemberAdder_AddMembers_Call{Call: _e.mock.On("AddMembers", ctx, roomId, memberIds, userId)}
}

func (_c *MockMemberAdder_AddMembers_Call) Run(run func(ctx context.Context, roomId uuid.UUID, memberIds []uuid.UUID, userId uuid.UUID)) *MockMemberAdder_AddMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockMemberAdder_AddMembers_Call) Return(_a0 error) *MockMemberAdder_AddMembers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMemberAdder_AddMembers_Call) RunAndReturn(run func(context.Context, uuid.UUID, []uuid.UUID, uuid.UUID) error) *MockMemberAdder_AddMembers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMemberAdder creates a new instance of MockMemberAdder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMemberAdder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMemberAdder {
	mock := &MockMemberAdder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
