// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "webby/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockTokenGetter is an autogenerated mock type for the TokenGetter type
type MockTokenGetter struct {
	mock.Mock
}

type MockTokenGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenGetter) EXPECT() *MockTokenGetter_Expecter {
	return &MockTokenGetter_Expecter{mock: &_m.Mock}
}

// GetByToken provides a mock function with given fields: token
func (_m *MockTokenGetter) GetByToken(token string) (*models.Room, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for GetByToken")
	}

	var r0 *models.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Room, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Room); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenGetter_GetByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByToken'
type MockTokenGetter_GetByToken_Call struct {
	*mock.Call
}

// GetByToken is a helper method to define mock.On call
//   - token string
func (_e *MockTokenGetter_Expecter) GetByToken(token interface{}) *MockTokenGetter_GetByToken_Call {
	return &MockTokenGetter_GetByToken_Call{Call: _e.mock.On("GetByToken", token)}
}

func (_c *MockTokenGetter_GetByToken_Call) Run(run func(token string)) *MockTokenGetter_GetByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTokenGetter_GetByToken_Call) Return(_a0 *models.Room, _a1 error) *MockTokenGetter_GetByToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenGetter_GetByToken_Call) RunAndReturn(run func(string) (*models.Room, error)) *MockTokenGetter_GetByToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenGetter creates a new instance of MockTokenGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenGetter {
	mock := &MockTokenGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
