// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/media/media.proto

package mediapb

type GetVideoRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

type VideoResponse struct {
	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title      string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Thumbnail  string `protobuf:"bytes,3,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	VideoUrl   string `protobuf:"bytes,4,opt,name=videoUrl,proto3" json:"videoUrl,omitempty"`
	PreviewUrl string `protobuf:"bytes,5,opt,name=previewUrl,proto3" json:"previewUrl,omitempty"`
}

type GetPlaylistRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

type PlaylistResponse struct {
	Id        string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title     string           `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Thumbnail string           `protobuf:"bytes,3,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Videos    []*VideoResponse `protobuf:"bytes,4,rep,name=videos,proto3" json:"videos,omitempty"`
}
