// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: proto/media/media.proto

package mediapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoRequest) Reset() {
	*x = GetVideoRequest{}
	mi := &file_proto_media_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoRequest) ProtoMessage() {}

func (x *GetVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoRequest.ProtoReflect.Descriptor instead.
func (*GetVideoRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_media_proto_rawDescGZIP(), []int{0}
}

func (x *GetVideoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type VideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,3,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,4,opt,name=videoUrl,proto3" json:"videoUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoResponse) Reset() {
	*x = VideoResponse{}
	mi := &file_proto_media_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoResponse) ProtoMessage() {}

func (x *VideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoResponse.ProtoReflect.Descriptor instead.
func (*VideoResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_media_proto_rawDescGZIP(), []int{1}
}

func (x *VideoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VideoResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoResponse) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *VideoResponse) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

type GetPlaylistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaylistRequest) Reset() {
	*x = GetPlaylistRequest{}
	mi := &file_proto_media_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaylistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaylistRequest) ProtoMessage() {}

func (x *GetPlaylistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaylistRequest.ProtoReflect.Descriptor instead.
func (*GetPlaylistRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_media_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlaylistRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetPlaylistRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPlaylistRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PlaylistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,3,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	Videos        []*VideoResponse       `protobuf:"bytes,5,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaylistResponse) Reset() {
	*x = PlaylistResponse{}
	mi := &file_proto_media_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaylistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistResponse) ProtoMessage() {}

func (x *PlaylistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistResponse.ProtoReflect.Descriptor instead.
func (*PlaylistResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_media_proto_rawDescGZIP(), []int{3}
}

func (x *PlaylistResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlaylistResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PlaylistResponse) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *PlaylistResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *PlaylistResponse) GetVideos() []*VideoResponse {
	if x != nil {
		return x.Videos
	}
	return nil
}

var File_proto_media_media_proto protoreflect.FileDescriptor

const file_proto_media_media_proto_rawDesc = "" +
	"\n" +
	"\x17proto/media/media.proto\x12\x05media\"!\n" +
	"\x0fGetVideoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"o\n" +
	"\rVideoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1c\n" +
	"\tthumbnail\x18\x03 \x01(\tR\tthumbnail\x12\x1a\n" +
	"\bvideoUrl\x18\x04 \x01(\tR\bvideoUrl\"T\n" +
	"\x12GetPlaylistRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize\"\xa4\x01\n" +
	"\x10PlaylistResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1c\n" +
	"\tthumbnail\x18\x03 \x01(\tR\tthumbnail\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x04 \x01(\x05R\n" +
	"totalCount\x12,\n" +
	"\x06videos\x18\x05 \x03(\v2\x14.media.VideoResponseR\x06videos2\x8b\x01\n" +
	"\fMediaService\x128\n" +
	"\bGetVideo\x12\x16.media.GetVideoRequest\x1a\x14.media.VideoResponse\x12A\n" +
	"\vGetPlaylist\x12\x19.media.GetPlaylistRequest\x1a\x17.media.PlaylistResponseB*Z(webby/room-service/internal/grpc/mediapbb\x06proto3"

var (
	file_proto_media_media_proto_rawDescOnce sync.Once
	file_proto_media_media_proto_rawDescData []byte
)

func file_proto_media_media_proto_rawDescGZIP() []byte {
	file_proto_media_media_proto_rawDescOnce.Do(func() {
		file_proto_media_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_media_media_proto_rawDesc), len(file_proto_media_media_proto_rawDesc)))
	})
	return file_proto_media_media_proto_rawDescData
}

var file_proto_media_media_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_media_media_proto_goTypes = []any{
	(*GetVideoRequest)(nil),    // 0: media.GetVideoRequest
	(*VideoResponse)(nil),      // 1: media.VideoResponse
	(*GetPlaylistRequest)(nil), // 2: media.GetPlaylistRequest
	(*PlaylistResponse)(nil),   // 3: media.PlaylistResponse
}
var file_proto_media_media_proto_depIdxs = []int32{
	1, // 0: media.PlaylistResponse.videos:type_name -> media.VideoResponse
	0, // 1: media.MediaService.GetVideo:input_type -> media.GetVideoRequest
	2, // 2: media.MediaService.GetPlaylist:input_type -> media.GetPlaylistRequest
	1, // 3: media.MediaService.GetVideo:output_type -> media.VideoResponse
	3, // 4: media.MediaService.GetPlaylist:output_type -> media.PlaylistResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_media_media_proto_init() }
func file_proto_media_media_proto_init() {
	if File_proto_media_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_media_media_proto_rawDesc), len(file_proto_media_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_media_media_proto_goTypes,
		DependencyIndexes: file_proto_media_media_proto_depIdxs,
		MessageInfos:      file_proto_media_media_proto_msgTypes,
	}.Build()
	File_proto_media_media_proto = out.File
	file_proto_media_media_proto_goTypes = nil
	file_proto_media_media_proto_depIdxs = nil
}
