// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	services "webby/vote-service/internal/services"

	uuid "github.com/google/uuid"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CastVote provides a mock function with given fields: ctx, voteId, choiceId, userId
func (_m *MockService) CastVote(ctx context.Context, voteId uuid.UUID, choiceId uuid.UUID, userId uuid.UUID) (*services.VoteDetail, error) {
	ret := _m.Called(ctx, voteId, choiceId, userId)

	if len(ret) == 0 {
		panic("no return value specified for CastVote")
	}

	var r0 *services.VoteDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (*services.VoteDetail, error)); ok {
		return rf(ctx, voteId, choiceId, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) *services.VoteDetail); ok {
		r0 = rf(ctx, voteId, choiceId, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.VoteDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, voteId, choiceId, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CastVote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CastVote'
type MockService_CastVote_Call struct {
	*mock.Call
}

// CastVote is a helper method to define mock.On call
//   - ctx context.Context
//   - voteId uuid.UUID
//   - choiceId uuid.UUID
//   - userId uuid.UUID
func (_e *MockService_Expecter) CastVote(ctx interface{}, voteId interface{}, choiceId interface{}, userId interface{}) *MockService_CastVote_Call {
	return &MockService_CastVote_Call{Call: _e.mock.On("CastVote", ctx, voteId, choiceId, userId)}
}

func (_c *MockService_CastVote_Call) Run(run func(ctx context.Context, voteId uuid.UUID, choiceId uuid.UUID, userId uuid.UUID)) *MockService_CastVote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_CastVote_Call) Return(_a0 *services.VoteDetail, _a1 error) *MockService_CastVote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CastVote_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (*services.VoteDetail, error)) *MockService_CastVote_Call {
	_c.Call.Return(run)
	return _c
}

// CreateVote provides a mock function with given fields: ctx, roomId, userId, voteType, voteText, durationSeconds, choices
func (_m *MockService) CreateVote(ctx context.Context, roomId uuid.UUID, userId uuid.UUID, voteType string, voteText string, durationSeconds int, choices []services.CreateChoiceInput) (*services.VoteDetail, error) {
	ret := _m.Called(ctx, roomId, userId, voteType, voteText, durationSeconds, choices)

	if len(ret) == 0 {
		panic("no return value specified for CreateVote")
	}

	var r0 *services.VoteDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, int, []services.CreateChoiceInput) (*services.VoteDetail, error)); ok {
		return rf(ctx, roomId, userId, voteType, voteText, durationSeconds, choices)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, int, []services.CreateChoiceInput) *services.VoteDetail); ok {
		r0 = rf(ctx, roomId, userId, voteType, voteText, durationSeconds, choices)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.VoteDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, string, int, []services.CreateChoiceInput) error); ok {
		r1 = rf(ctx, roomId, userId, voteType, voteText, durationSeconds, choices)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateVote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVote'
type MockService_CreateVote_Call struct {
	*mock.Call
}

// CreateVote is a helper method to define mock.On call
//   - ctx context.Context
//   - roomId uuid.UUID
//   - userId uuid.UUID
//   - voteType string
//   - voteText string
//   - durationSeconds int
//   - choices []services.CreateChoiceInput
func (_e *MockService_Expecter) CreateVote(ctx interface{}, roomId interface{}, userId interface{}, voteType interface{}, voteText interface{}, durationSeconds interface{}, choices interface{}) *MockService_CreateVote_Call {
	return &MockService_CreateVote_Call{Call: _e.mock.On("CreateVote", ctx, roomId, userId, voteType, voteText, durationSeconds, choices)}
}

func (_c *MockService_CreateVote_Call) Run(run func(ctx context.Context, roomId uuid.UUID, userId uuid.UUID, voteType string, voteText string, durationSeconds int, choices []services.CreateChoiceInput)) *MockService_CreateVote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].(string), args[5].(int), args[6].([]services.CreateChoiceInput))
	})
	return _c
}

func (_c *MockService_CreateVote_Call) Return(_a0 *services.VoteDetail, _a1 error) *MockService_CreateVote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateVote_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string, string, int, []services.CreateChoiceInput) (*services.VoteDetail, error)) *MockService_CreateVote_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteVote provides a mock function with given fields: ctx, voteId, userId
func (_m *MockService) DeleteVote(ctx context.Context, voteId uuid.UUID, userId uuid.UUID) error {
	ret := _m.Called(ctx, voteId, userId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, voteId, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteVote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVote'
type MockService_DeleteVote_Call struct {
	*mock.Call
}

// DeleteVote is a helper method to define mock.On call
//   - ctx context.Context
//   - voteId uuid.UUID
//   - userId uuid.UUID
func (_e *MockService_Expecter) DeleteVote(ctx interface{}, voteId interface{}, userId interface{}) *MockService_DeleteVote_Call {
	return &MockService_DeleteVote_Call{Call: _e.mock.On("DeleteVote", ctx, voteId, userId)}
}

func (_c *MockService_DeleteVote_Call) Run(run func(ctx context.Context, voteId uuid.UUID, userId uuid.UUID)) *MockService_DeleteVote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_DeleteVote_Call) Return(_a0 error) *MockService_DeleteVote_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteVote_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockService_DeleteVote_Call {
	_c.Call.Return(run)
	return _c
}

// GetVote provides a mock function with given fields: ctx, voteId, userId
func (_m *MockService) GetVote(ctx context.Context, voteId uuid.UUID, userId uuid.UUID) (*services.VoteDetail, error) {
	ret := _m.Called(ctx, voteId, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetVote")
	}

	var r0 *services.VoteDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*services.VoteDetail, error)); ok {
		return rf(ctx, voteId, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *services.VoteDetail); ok {
		r0 = rf(ctx, voteId, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.VoteDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, voteId, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetVote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVote'
type MockService_GetVote_Call struct {
	*mock.Call
}

// GetVote is a helper method to define mock.On call
//   - ctx context.Context
//   - voteId uuid.UUID
//   - userId uuid.UUID
func (_e *MockService_Expecter) GetVote(ctx interface{}, voteId interface{}, userId interface{}) *MockService_GetVote_Call {
	return &MockService_GetVote_Call{Call: _e.mock.On("GetVote", ctx, voteId, userId)}
}

func (_c *MockService_GetVote_Call) Run(run func(ctx context.Context, voteId uuid.UUID, userId uuid.UUID)) *MockService_GetVote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_GetVote_Call) Return(_a0 *services.VoteDetail, _a1 error) *MockService_GetVote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetVote_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*services.VoteDetail, error)) *MockService_GetVote_Call {
	_c.Call.Return(run)
	return _c
}

// ListVotes provides a mock function with given fields: ctx, roomId, userId
func (_m *MockService) ListVotes(ctx context.Context, roomId uuid.UUID, userId uuid.UUID) ([]services.VoteDetail, error) {
	ret := _m.Called(ctx, roomId, userId)

	if len(ret) == 0 {
		panic("no return value specified for ListVotes")
	}

	var r0 []services.VoteDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]services.VoteDetail, error)); ok {
		return rf(ctx, roomId, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []services.VoteDetail); ok {
		r0 = rf(ctx, roomId, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]services.VoteDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, roomId, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListVotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVotes'
type MockService_ListVotes_Call struct {
	*mock.Call
}

// ListVotes is a helper method to define mock.On call
//   - ctx context.Context
//   - roomId uuid.UUID
//   - userId uuid.UUID
func (_e *MockService_Expecter) ListVotes(ctx interface{}, roomId interface{}, userId interface{}) *MockService_ListVotes_Call {
	return &MockService_ListVotes_Call{Call: _e.mock.On("ListVotes", ctx, roomId, userId)}
}

func (_c *MockService_ListVotes_Call) Run(run func(ctx context.Context, roomId uuid.UUID, userId uuid.UUID)) *MockService_ListVotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_ListVotes_Call) Return(_a0 []services.VoteDetail, _a1 error) *MockService_ListVotes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListVotes_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]services.VoteDetail, error)) *MockService_ListVotes_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveVote provides a mock function with given fields: ctx, voteId, userId
func (_m *MockService) RemoveVote(ctx context.Context, voteId uuid.UUID, userId uuid.UUID) (*services.VoteDetail, error) {
	ret := _m.Called(ctx, voteId, userId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveVote")
	}

	var r0 *services.VoteDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*services.VoteDetail, error)); ok {
		return rf(ctx, voteId, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *services.VoteDetail); ok {
		r0 = rf(ctx, voteId, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.VoteDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, voteId, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_RemoveVote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveVote'
type MockService_RemoveVote_Call struct {
	*mock.Call
}

// RemoveVote is a helper method to define mock.On call
//   - ctx context.Context
//   - voteId uuid.UUID
//   - userId uuid.UUID
func (_e *MockService_Expecter) RemoveVote(ctx interface{}, voteId interface{}, userId interface{}) *MockService_RemoveVote_Call {
	return &MockService_RemoveVote_Call{Call: _e.mock.On("RemoveVote", ctx, voteId, userId)}
}

func (_c *MockService_RemoveVote_Call) Run(run func(ctx context.Context, voteId uuid.UUID, userId uuid.UUID)) *MockService_RemoveVote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_RemoveVote_Call) Return(_a0 *services.VoteDetail, _a1 error) *MockService_RemoveVote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_RemoveVote_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*services.VoteDetail, error)) *MockService_RemoveVote_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
