// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "webby/vote-service/internal/models"

	uuid "github.com/google/uuid"
)

// Mockservice is an autogenerated mock type for the service type
type Mockservice struct {
	mock.Mock
}

type Mockservice_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockservice) EXPECT() *Mockservice_Expecter {
	return &Mockservice_Expecter{mock: &_m.Mock}
}

// CastVote provides a mock function with given fields: ctx, voteId, choiceId, userId
func (_m *Mockservice) CastVote(ctx context.Context, voteId uuid.UUID, choiceId uuid.UUID, userId uuid.UUID) error {
	ret := _m.Called(ctx, voteId, choiceId, userId)

	if len(ret) == 0 {
		panic("no return value specified for CastVote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, voteId, choiceId, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mockservice_CastVote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CastVote'
type Mockservice_CastVote_Call struct {
	*mock.Call
}

// CastVote is a helper method to define mock.On call
//   - ctx context.Context
//   - voteId uuid.UUID
//   - choiceId uuid.UUID
//   - userId uuid.UUID
func (_e *Mockservice_Expecter) CastVote(ctx interface{}, voteId interface{}, choiceId interface{}, userId interface{}) *Mockservice_CastVote_Call {
	return &Mockservice_CastVote_Call{Call: _e.mock.On("CastVote", ctx, voteId, choiceId, userId)}
}

func (_c *Mockservice_CastVote_Call) Run(run func(ctx context.Context, voteId uuid.UUID, choiceId uuid.UUID, userId uuid.UUID)) *Mockservice_CastVote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *Mockservice_CastVote_Call) Return(_a0 error) *Mockservice_CastVote_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mockservice_CastVote_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) *Mockservice_CastVote_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithRightChoice provides a mock function with given fields: ctx, roomID, userID, voteText, duration, choices
func (_m *Mockservice) CreateWithRightChoice(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, voteText string, duration int, choices []string) error {
	ret := _m.Called(ctx, roomID, userID, voteText, duration, choices)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithRightChoice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, int, []string) error); ok {
		r0 = rf(ctx, roomID, userID, voteText, duration, choices)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mockservice_CreateWithRightChoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithRightChoice'
type Mockservice_CreateWithRightChoice_Call struct {
	*mock.Call
}

// CreateWithRightChoice is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
//   - voteText string
//   - duration int
//   - choices []string
func (_e *Mockservice_Expecter) CreateWithRightChoice(ctx interface{}, roomID interface{}, userID interface{}, voteText interface{}, duration interface{}, choices interface{}) *Mockservice_CreateWithRightChoice_Call {
	return &Mockservice_CreateWithRightChoice_Call{Call: _e.mock.On("CreateWithRightChoice", ctx, roomID, userID, voteText, duration, choices)}
}

func (_c *Mockservice_CreateWithRightChoice_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, voteText string, duration int, choices []string)) *Mockservice_CreateWithRightChoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].(int), args[5].([]string))
	})
	return _c
}

func (_c *Mockservice_CreateWithRightChoice_Call) Return(_a0 error) *Mockservice_CreateWithRightChoice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mockservice_CreateWithRightChoice_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string, int, []string) error) *Mockservice_CreateWithRightChoice_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteVote provides a mock function with given fields: ctx, voteId, userId
func (_m *Mockservice) DeleteVote(ctx context.Context, voteId uuid.UUID, userId uuid.UUID) error {
	ret := _m.Called(ctx, voteId, userId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, voteId, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mockservice_DeleteVote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVote'
type Mockservice_DeleteVote_Call struct {
	*mock.Call
}

// DeleteVote is a helper method to define mock.On call
//   - ctx context.Context
//   - voteId uuid.UUID
//   - userId uuid.UUID
func (_e *Mockservice_Expecter) DeleteVote(ctx interface{}, voteId interface{}, userId interface{}) *Mockservice_DeleteVote_Call {
	return &Mockservice_DeleteVote_Call{Call: _e.mock.On("DeleteVote", ctx, voteId, userId)}
}

func (_c *Mockservice_DeleteVote_Call) Run(run func(ctx context.Context, voteId uuid.UUID, userId uuid.UUID)) *Mockservice_DeleteVote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Mockservice_DeleteVote_Call) Return(_a0 error) *Mockservice_DeleteVote_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mockservice_DeleteVote_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *Mockservice_DeleteVote_Call {
	_c.Call.Return(run)
	return _c
}

// ListVotes provides a mock function with given fields: ctx, roomID, userID
func (_m *Mockservice) ListVotes(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) ([]models.EnrichedVoting, error) {
	ret := _m.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListVotes")
	}

	var r0 []models.EnrichedVoting
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]models.EnrichedVoting, error)); ok {
		return rf(ctx, roomID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []models.EnrichedVoting); ok {
		r0 = rf(ctx, roomID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.EnrichedVoting)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, roomID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mockservice_ListVotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVotes'
type Mockservice_ListVotes_Call struct {
	*mock.Call
}

// ListVotes is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
func (_e *Mockservice_Expecter) ListVotes(ctx interface{}, roomID interface{}, userID interface{}) *Mockservice_ListVotes_Call {
	return &Mockservice_ListVotes_Call{Call: _e.mock.On("ListVotes", ctx, roomID, userID)}
}

func (_c *Mockservice_ListVotes_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID)) *Mockservice_ListVotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Mockservice_ListVotes_Call) Return(_a0 []models.EnrichedVoting, _a1 error) *Mockservice_ListVotes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mockservice_ListVotes_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]models.EnrichedVoting, error)) *Mockservice_ListVotes_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveVote provides a mock function with given fields: ctx, voteId, userId
func (_m *Mockservice) RemoveVote(ctx context.Context, voteId uuid.UUID, userId uuid.UUID) error {
	ret := _m.Called(ctx, voteId, userId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveVote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, voteId, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mockservice_RemoveVote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveVote'
type Mockservice_RemoveVote_Call struct {
	*mock.Call
}

// RemoveVote is a helper method to define mock.On call
//   - ctx context.Context
//   - voteId uuid.UUID
//   - userId uuid.UUID
func (_e *Mockservice_Expecter) RemoveVote(ctx interface{}, voteId interface{}, userId interface{}) *Mockservice_RemoveVote_Call {
	return &Mockservice_RemoveVote_Call{Call: _e.mock.On("RemoveVote", ctx, voteId, userId)}
}

func (_c *Mockservice_RemoveVote_Call) Run(run func(ctx context.Context, voteId uuid.UUID, userId uuid.UUID)) *Mockservice_RemoveVote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Mockservice_RemoveVote_Call) Return(_a0 error) *Mockservice_RemoveVote_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mockservice_RemoveVote_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *Mockservice_RemoveVote_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveVoting provides a mock function with given fields: ctx, roomID, userID, voteID, rightChoice
func (_m *Mockservice) ResolveVoting(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, voteID uuid.UUID, rightChoice string) error {
	ret := _m.Called(ctx, roomID, userID, voteID, rightChoice)

	if len(ret) == 0 {
		panic("no return value specified for ResolveVoting")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, roomID, userID, voteID, rightChoice)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mockservice_ResolveVoting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveVoting'
type Mockservice_ResolveVoting_Call struct {
	*mock.Call
}

// ResolveVoting is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
//   - voteID uuid.UUID
//   - rightChoice string
func (_e *Mockservice_Expecter) ResolveVoting(ctx interface{}, roomID interface{}, userID interface{}, voteID interface{}, rightChoice interface{}) *Mockservice_ResolveVoting_Call {
	return &Mockservice_ResolveVoting_Call{Call: _e.mock.On("ResolveVoting", ctx, roomID, userID, voteID, rightChoice)}
}

func (_c *Mockservice_ResolveVoting_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, voteID uuid.UUID, rightChoice string)) *Mockservice_ResolveVoting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID), args[4].(string))
	})
	return _c
}

func (_c *Mockservice_ResolveVoting_Call) Return(_a0 error) *Mockservice_ResolveVoting_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mockservice_ResolveVoting_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, string) error) *Mockservice_ResolveVoting_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockservice creates a new instance of Mockservice. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockservice(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockservice {
	mock := &Mockservice{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
