// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	models "webby/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockCategoryService is an autogenerated mock type for the CategoryService type
type MockCategoryService struct {
	mock.Mock
}

type MockCategoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryService) EXPECT() *MockCategoryService_Expecter {
	return &MockCategoryService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, name
func (_m *MockCategoryService) Create(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategoryService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCategoryService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockCategoryService_Expecter) Create(ctx interface{}, name interface{}) *MockCategoryService_Create_Call {
	return &MockCategoryService_Create_Call{Call: _e.mock.On("Create", ctx, name)}
}

func (_c *MockCategoryService_Create_Call) Run(run func(ctx context.Context, name string)) *MockCategoryService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCategoryService_Create_Call) Return(_a0 error) *MockCategoryService_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategoryService_Create_Call) RunAndReturn(run func(context.Context, string) error) *MockCategoryService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name
func (_m *MockCategoryService) Delete(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategoryService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCategoryService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockCategoryService_Expecter) Delete(ctx interface{}, name interface{}) *MockCategoryService_Delete_Call {
	return &MockCategoryService_Delete_Call{Call: _e.mock.On("Delete", ctx, name)}
}

func (_c *MockCategoryService_Delete_Call) Run(run func(ctx context.Context, name string)) *MockCategoryService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCategoryService_Delete_Call) Return(_a0 error) *MockCategoryService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategoryService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockCategoryService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, search, page, limit
func (_m *MockCategoryService) List(ctx context.Context, search string, page int, limit int) ([]models.Category, int64, error) {
	ret := _m.Called(ctx, search, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Category
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]models.Category, int64, error)); ok {
		return rf(ctx, search, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []models.Category); ok {
		r0 = rf(ctx, search, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int64); ok {
		r1 = rf(ctx, search, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, search, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCategoryService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCategoryService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - search string
//   - page int
//   - limit int
func (_e *MockCategoryService_Expecter) List(ctx interface{}, search interface{}, page interface{}, limit interface{}) *MockCategoryService_List_Call {
	return &MockCategoryService_List_Call{Call: _e.mock.On("List", ctx, search, page, limit)}
}

func (_c *MockCategoryService_List_Call) Run(run func(ctx context.Context, search string, page int, limit int)) *MockCategoryService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockCategoryService_List_Call) Return(_a0 []models.Category, _a1 int64, _a2 error) *MockCategoryService_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCategoryService_List_Call) RunAndReturn(run func(context.Context, string, int, int) ([]models.Category, int64, error)) *MockCategoryService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, oldName, newName
func (_m *MockCategoryService) Update(ctx context.Context, oldName string, newName string) error {
	ret := _m.Called(ctx, oldName, newName)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, oldName, newName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategoryService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCategoryService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - oldName string
//   - newName string
func (_e *MockCategoryService_Expecter) Update(ctx interface{}, oldName interface{}, newName interface{}) *MockCategoryService_Update_Call {
	return &MockCategoryService_Update_Call{Call: _e.mock.On("Update", ctx, oldName, newName)}
}

func (_c *MockCategoryService_Update_Call) Run(run func(ctx context.Context, oldName string, newName string)) *MockCategoryService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockCategoryService_Update_Call) Return(_a0 error) *MockCategoryService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategoryService_Update_Call) RunAndReturn(run func(context.Context, string, string) error) *MockCategoryService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCategoryService creates a new instance of MockCategoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryService {
	mock := &MockCategoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
