// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "webby/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockPublicLister is an autogenerated mock type for the PublicLister type
type MockPublicLister struct {
	mock.Mock
}

type MockPublicLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublicLister) EXPECT() *MockPublicLister_Expecter {
	return &MockPublicLister_Expecter{mock: &_m.Mock}
}

// ListPublic provides a mock function with given fields: page, limit, search, categoryId
func (_m *MockPublicLister) ListPublic(page int, limit int, search string, categoryId *uuid.UUID) ([]models.Room, int64, error) {
	ret := _m.Called(page, limit, search, categoryId)

	if len(ret) == 0 {
		panic("no return value specified for ListPublic")
	}

	var r0 []models.Room
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, string, *uuid.UUID) ([]models.Room, int64, error)); ok {
		return rf(page, limit, search, categoryId)
	}
	if rf, ok := ret.Get(0).(func(int, int, string, *uuid.UUID) []models.Room); ok {
		r0 = rf(page, limit, search, categoryId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string, *uuid.UUID) int64); ok {
		r1 = rf(page, limit, search, categoryId)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int, string, *uuid.UUID) error); ok {
		r2 = rf(page, limit, search, categoryId)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockPublicLister_ListPublic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPublic'
type MockPublicLister_ListPublic_Call struct {
	*mock.Call
}

// ListPublic is a helper method to define mock.On call
//   - page int
//   - limit int
//   - search string
//   - categoryId *uuid.UUID
func (_e *MockPublicLister_Expecter) ListPublic(page interface{}, limit interface{}, search interface{}, categoryId interface{}) *MockPublicLister_ListPublic_Call {
	return &MockPublicLister_ListPublic_Call{Call: _e.mock.On("ListPublic", page, limit, search, categoryId)}
}

func (_c *MockPublicLister_ListPublic_Call) Run(run func(page int, limit int, search string, categoryId *uuid.UUID)) *MockPublicLister_ListPublic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int), args[2].(string), args[3].(*uuid.UUID))
	})
	return _c
}

func (_c *MockPublicLister_ListPublic_Call) Return(_a0 []models.Room, _a1 int64, _a2 error) *MockPublicLister_ListPublic_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockPublicLister_ListPublic_Call) RunAndReturn(run func(int, int, string, *uuid.UUID) ([]models.Room, int64, error)) *MockPublicLister_ListPublic_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPublicLister creates a new instance of MockPublicLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublicLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublicLister {
	mock := &MockPublicLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
