// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "webby/chat-service/internal/models"

	uuid "github.com/google/uuid"
)

// MockmessageService is an autogenerated mock type for the messageService type
type MockmessageService struct {
	mock.Mock
}

type MockmessageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockmessageService) EXPECT() *MockmessageService_Expecter {
	return &MockmessageService_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, chatID, messageID, userID
func (_m *MockmessageService) Delete(ctx context.Context, chatID uuid.UUID, messageID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, chatID, messageID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, chatID, messageID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockmessageService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockmessageService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uuid.UUID
//   - messageID uuid.UUID
//   - userID uuid.UUID
func (_e *MockmessageService_Expecter) Delete(ctx interface{}, chatID interface{}, messageID interface{}, userID interface{}) *MockmessageService_Delete_Call {
	return &MockmessageService_Delete_Call{Call: _e.mock.On("Delete", ctx, chatID, messageID, userID)}
}

func (_c *MockmessageService_Delete_Call) Run(run func(ctx context.Context, chatID uuid.UUID, messageID uuid.UUID, userID uuid.UUID)) *MockmessageService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockmessageService_Delete_Call) Return(_a0 error) *MockmessageService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockmessageService_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) *MockmessageService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, chatID, userID, limit, page
func (_m *MockmessageService) List(ctx context.Context, chatID uuid.UUID, userID uuid.UUID, limit int, page int) ([]models.RichMessage, int64, error) {
	ret := _m.Called(ctx, chatID, userID, limit, page)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.RichMessage
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int) ([]models.RichMessage, int64, error)); ok {
		return rf(ctx, chatID, userID, limit, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int) []models.RichMessage); ok {
		r0 = rf(ctx, chatID, userID, limit, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.RichMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int, int) int64); ok {
		r1 = rf(ctx, chatID, userID, limit, page)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, chatID, userID, limit, page)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockmessageService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockmessageService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uuid.UUID
//   - userID uuid.UUID
//   - limit int
//   - page int
func (_e *MockmessageService_Expecter) List(ctx interface{}, chatID interface{}, userID interface{}, limit interface{}, page interface{}) *MockmessageService_List_Call {
	return &MockmessageService_List_Call{Call: _e.mock.On("List", ctx, chatID, userID, limit, page)}
}

func (_c *MockmessageService_List_Call) Run(run func(ctx context.Context, chatID uuid.UUID, userID uuid.UUID, limit int, page int)) *MockmessageService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockmessageService_List_Call) Return(_a0 []models.RichMessage, _a1 int64, _a2 error) *MockmessageService_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockmessageService_List_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, int, int) ([]models.RichMessage, int64, error)) *MockmessageService_List_Call {
	_c.Call.Return(run)
	return _c
}

// SaveMessage provides a mock function with given fields: ctx, senderID, chatID, content
func (_m *MockmessageService) SaveMessage(ctx context.Context, senderID uuid.UUID, chatID uuid.UUID, content string) error {
	ret := _m.Called(ctx, senderID, chatID, content)

	if len(ret) == 0 {
		panic("no return value specified for SaveMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, senderID, chatID, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockmessageService_SaveMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMessage'
type MockmessageService_SaveMessage_Call struct {
	*mock.Call
}

// SaveMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - senderID uuid.UUID
//   - chatID uuid.UUID
//   - content string
func (_e *MockmessageService_Expecter) SaveMessage(ctx interface{}, senderID interface{}, chatID interface{}, content interface{}) *MockmessageService_SaveMessage_Call {
	return &MockmessageService_SaveMessage_Call{Call: _e.mock.On("SaveMessage", ctx, senderID, chatID, content)}
}

func (_c *MockmessageService_SaveMessage_Call) Run(run func(ctx context.Context, senderID uuid.UUID, chatID uuid.UUID, content string)) *MockmessageService_SaveMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockmessageService_SaveMessage_Call) Return(_a0 error) *MockmessageService_SaveMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockmessageService_SaveMessage_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) error) *MockmessageService_SaveMessage_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, chatID, messageID, userID, content
func (_m *MockmessageService) Update(ctx context.Context, chatID uuid.UUID, messageID uuid.UUID, userID uuid.UUID, content string) error {
	ret := _m.Called(ctx, chatID, messageID, userID, content)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, chatID, messageID, userID, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockmessageService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockmessageService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uuid.UUID
//   - messageID uuid.UUID
//   - userID uuid.UUID
//   - content string
func (_e *MockmessageService_Expecter) Update(ctx interface{}, chatID interface{}, messageID interface{}, userID interface{}, content interface{}) *MockmessageService_Update_Call {
	return &MockmessageService_Update_Call{Call: _e.mock.On("Update", ctx, chatID, messageID, userID, content)}
}

func (_c *MockmessageService_Update_Call) Run(run func(ctx context.Context, chatID uuid.UUID, messageID uuid.UUID, userID uuid.UUID, content string)) *MockmessageService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID), args[4].(string))
	})
	return _c
}

func (_c *MockmessageService_Update_Call) Return(_a0 error) *MockmessageService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockmessageService_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, string) error) *MockmessageService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockmessageService creates a new instance of MockmessageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockmessageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockmessageService {
	mock := &MockmessageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
