// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockmessageService is an autogenerated mock type for the messageService type
type MockmessageService struct {
	mock.Mock
}

type MockmessageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockmessageService) EXPECT() *MockmessageService_Expecter {
	return &MockmessageService_Expecter{mock: &_m.Mock}
}

// SaveMessage provides a mock function with given fields: ctx, senderID, chatID, content
func (_m *MockmessageService) SaveMessage(ctx context.Context, senderID uuid.UUID, chatID uuid.UUID, content string) error {
	ret := _m.Called(ctx, senderID, chatID, content)

	if len(ret) == 0 {
		panic("no return value specified for SaveMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, senderID, chatID, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockmessageService_SaveMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMessage'
type MockmessageService_SaveMessage_Call struct {
	*mock.Call
}

// SaveMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - senderID uuid.UUID
//   - chatID uuid.UUID
//   - content string
func (_e *MockmessageService_Expecter) SaveMessage(ctx interface{}, senderID interface{}, chatID interface{}, content interface{}) *MockmessageService_SaveMessage_Call {
	return &MockmessageService_SaveMessage_Call{Call: _e.mock.On("SaveMessage", ctx, senderID, chatID, content)}
}

func (_c *MockmessageService_SaveMessage_Call) Run(run func(ctx context.Context, senderID uuid.UUID, chatID uuid.UUID, content string)) *MockmessageService_SaveMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockmessageService_SaveMessage_Call) Return(_a0 error) *MockmessageService_SaveMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockmessageService_SaveMessage_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) error) *MockmessageService_SaveMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockmessageService creates a new instance of MockmessageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockmessageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockmessageService {
	mock := &MockmessageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
