// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "webby/chat-service/internal/models"

	uuid "github.com/google/uuid"
)

// MockchatService is an autogenerated mock type for the chatService type
type MockchatService struct {
	mock.Mock
}

type MockchatService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockchatService) EXPECT() *MockchatService_Expecter {
	return &MockchatService_Expecter{mock: &_m.Mock}
}

// CreatePrivate provides a mock function with given fields: ctx, initiatorID, targetID
func (_m *MockchatService) CreatePrivate(ctx context.Context, initiatorID uuid.UUID, targetID uuid.UUID) (*models.Chat, error) {
	ret := _m.Called(ctx, initiatorID, targetID)

	if len(ret) == 0 {
		panic("no return value specified for CreatePrivate")
	}

	var r0 *models.Chat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.Chat, error)); ok {
		return rf(ctx, initiatorID, targetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.Chat); ok {
		r0 = rf(ctx, initiatorID, targetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Chat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, initiatorID, targetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockchatService_CreatePrivate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePrivate'
type MockchatService_CreatePrivate_Call struct {
	*mock.Call
}

// CreatePrivate is a helper method to define mock.On call
//   - ctx context.Context
//   - initiatorID uuid.UUID
//   - targetID uuid.UUID
func (_e *MockchatService_Expecter) CreatePrivate(ctx interface{}, initiatorID interface{}, targetID interface{}) *MockchatService_CreatePrivate_Call {
	return &MockchatService_CreatePrivate_Call{Call: _e.mock.On("CreatePrivate", ctx, initiatorID, targetID)}
}

func (_c *MockchatService_CreatePrivate_Call) Run(run func(ctx context.Context, initiatorID uuid.UUID, targetID uuid.UUID)) *MockchatService_CreatePrivate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockchatService_CreatePrivate_Call) Return(_a0 *models.Chat, _a1 error) *MockchatService_CreatePrivate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockchatService_CreatePrivate_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*models.Chat, error)) *MockchatService_CreatePrivate_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, chatID
func (_m *MockchatService) Delete(ctx context.Context, userID uuid.UUID, chatID uuid.UUID) error {
	ret := _m.Called(ctx, userID, chatID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, chatID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockchatService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockchatService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - chatID uuid.UUID
func (_e *MockchatService_Expecter) Delete(ctx interface{}, userID interface{}, chatID interface{}) *MockchatService_Delete_Call {
	return &MockchatService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, chatID)}
}

func (_c *MockchatService_Delete_Call) Run(run func(ctx context.Context, userID uuid.UUID, chatID uuid.UUID)) *MockchatService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockchatService_Delete_Call) Return(_a0 error) *MockchatService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockchatService_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockchatService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, chatID, userID
func (_m *MockchatService) GetByID(ctx context.Context, chatID uuid.UUID, userID uuid.UUID) (*models.EnrichedChat, error) {
	ret := _m.Called(ctx, chatID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.EnrichedChat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.EnrichedChat, error)); ok {
		return rf(ctx, chatID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.EnrichedChat); ok {
		r0 = rf(ctx, chatID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EnrichedChat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, chatID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockchatService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockchatService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uuid.UUID
//   - userID uuid.UUID
func (_e *MockchatService_Expecter) GetByID(ctx interface{}, chatID interface{}, userID interface{}) *MockchatService_GetByID_Call {
	return &MockchatService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, chatID, userID)}
}

func (_c *MockchatService_GetByID_Call) Run(run func(ctx context.Context, chatID uuid.UUID, userID uuid.UUID)) *MockchatService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockchatService_GetByID_Call) Return(_a0 *models.EnrichedChat, _a1 error) *MockchatService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockchatService_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*models.EnrichedChat, error)) *MockchatService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// History provides a mock function with given fields: ctx, userID, page, limit, search
func (_m *MockchatService) History(ctx context.Context, userID uuid.UUID, page int, limit int, search string) ([]models.ChatHistoryItem, int, error) {
	ret := _m.Called(ctx, userID, page, limit, search)

	if len(ret) == 0 {
		panic("no return value specified for History")
	}

	var r0 []models.ChatHistoryItem
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int, string) ([]models.ChatHistoryItem, int, error)); ok {
		return rf(ctx, userID, page, limit, search)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int, string) []models.ChatHistoryItem); ok {
		r0 = rf(ctx, userID, page, limit, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ChatHistoryItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int, string) int); ok {
		r1 = rf(ctx, userID, page, limit, search)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int, string) error); ok {
		r2 = rf(ctx, userID, page, limit, search)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockchatService_History_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'History'
type MockchatService_History_Call struct {
	*mock.Call
}

// History is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - page int
//   - limit int
//   - search string
func (_e *MockchatService_Expecter) History(ctx interface{}, userID interface{}, page interface{}, limit interface{}, search interface{}) *MockchatService_History_Call {
	return &MockchatService_History_Call{Call: _e.mock.On("History", ctx, userID, page, limit, search)}
}

func (_c *MockchatService_History_Call) Run(run func(ctx context.Context, userID uuid.UUID, page int, limit int, search string)) *MockchatService_History_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int), args[4].(string))
	})
	return _c
}

func (_c *MockchatService_History_Call) Return(_a0 []models.ChatHistoryItem, _a1 int, _a2 error) *MockchatService_History_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockchatService_History_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int, string) ([]models.ChatHistoryItem, int, error)) *MockchatService_History_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockchatService creates a new instance of MockchatService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockchatService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockchatService {
	mock := &MockchatService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
