apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-getaway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-getaway
  template:
    metadata:
      labels:
        app: api-getaway
    spec:
      containers:
      - name: api-getaway
        image: docker-registry/server-api-gateway:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: JwtOptions__AccessSecretKey
          valueFrom:
            secretKeyRef:
              name: webby-secrets
              key: JwtAccessSecretKey
        - name: JwtOptions__AccessExpiresDuration
          valueFrom:
            secretKeyRef:
              name: webby-secrets
              key: JwtAccessExpiresDuration
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10